-- Apply `20260926_100000_editions_collection` on a host that cannot run the
-- migration (docs/DEPLOY.md).
--
--   docker exec now-postgres psql -U now -d <city> -v ON_ERROR_STOP=1 \
--     -f /tmp/editions-collection.sql
--
-- Purely additive (new tables/types only, nothing existing is touched), so
-- unlike `articles-slug.sql` there is no "must run before the image that
-- needs it" ordering hazard against already-deployed code — nothing reads
-- `editions` yet. Still, run it before the image whose Editorial nav offers
-- the Editions collection, for the same reason every SQL twin in this
-- package exists: the runner image cannot apply it itself.
--
-- Copied verbatim from the migration's `up()`. See that file's own
-- docstring for how each column/index/constraint name was derived (this
-- was hand-authored against a live schema's confirmed generation shape,
-- not machine-generated by `payload migrate:create` — read that note
-- before assuming this is byte-identical to what Payload's own generator
-- would produce).

BEGIN;

CREATE TYPE "public"."enum_editions_status" AS ENUM('draft', 'published');
CREATE TYPE "public"."enum__editions_v_version_status" AS ENUM('draft', 'published');

CREATE TABLE "editions" (
  "id" serial PRIMARY KEY NOT NULL,
  "title" varchar,
  "issue_label" varchar,
  "issue_date" timestamp(3) with time zone,
  "cover_id" integer,
  "on_sale_at" timestamp(3) with time zone,
  "sold_out" boolean DEFAULT false,
  "price_idr" numeric,
  "replica_pdf_id" integer,
  "notes" varchar,
  "updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  "created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  "_status" "public"."enum_editions_status" DEFAULT 'draft'
);

CREATE TABLE "editions_contents" (
  "_order" integer NOT NULL,
  "_parent_id" integer NOT NULL,
  "id" varchar PRIMARY KEY NOT NULL,
  "heading" varchar,
  "article_id" integer,
  "blurb" varchar
);

CREATE TABLE "_editions_v" (
  "id" serial PRIMARY KEY NOT NULL,
  "parent_id" integer,
  "version_title" varchar,
  "version_issue_label" varchar,
  "version_issue_date" timestamp(3) with time zone,
  "version_cover_id" integer,
  "version_on_sale_at" timestamp(3) with time zone,
  "version_sold_out" boolean DEFAULT false,
  "version_price_idr" numeric,
  "version_replica_pdf_id" integer,
  "version_notes" varchar,
  "version_updated_at" timestamp(3) with time zone,
  "version_created_at" timestamp(3) with time zone,
  "version__status" "public"."enum__editions_v_version_status" DEFAULT 'draft',
  "created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "_editions_v_version_contents" (
  "_order" integer NOT NULL,
  "_parent_id" integer NOT NULL,
  "id" varchar PRIMARY KEY NOT NULL,
  "heading" varchar,
  "article_id" integer,
  "blurb" varchar
);

ALTER TABLE "editions" ADD CONSTRAINT "editions_cover_id_media_id_fk"
  FOREIGN KEY ("cover_id") REFERENCES "media"("id") ON DELETE SET NULL;
ALTER TABLE "editions" ADD CONSTRAINT "editions_replica_pdf_id_media_id_fk"
  FOREIGN KEY ("replica_pdf_id") REFERENCES "media"("id") ON DELETE SET NULL;

ALTER TABLE "editions_contents" ADD CONSTRAINT "editions_contents_parent_id_fk"
  FOREIGN KEY ("_parent_id") REFERENCES "editions"("id") ON DELETE CASCADE;
ALTER TABLE "editions_contents" ADD CONSTRAINT "editions_contents_article_id_articles_id_fk"
  FOREIGN KEY ("article_id") REFERENCES "articles"("id") ON DELETE SET NULL;

ALTER TABLE "_editions_v" ADD CONSTRAINT "_editions_v_parent_id_editions_id_fk"
  FOREIGN KEY ("parent_id") REFERENCES "editions"("id") ON DELETE SET NULL;
ALTER TABLE "_editions_v" ADD CONSTRAINT "_editions_v_version_cover_id_media_id_fk"
  FOREIGN KEY ("version_cover_id") REFERENCES "media"("id") ON DELETE SET NULL;
ALTER TABLE "_editions_v" ADD CONSTRAINT "_editions_v_version_replica_pdf_id_media_id_fk"
  FOREIGN KEY ("version_replica_pdf_id") REFERENCES "media"("id") ON DELETE SET NULL;

ALTER TABLE "_editions_v_version_contents" ADD CONSTRAINT "_editions_v_version_contents_parent_id_fk"
  FOREIGN KEY ("_parent_id") REFERENCES "_editions_v"("id") ON DELETE CASCADE;
ALTER TABLE "_editions_v_version_contents" ADD CONSTRAINT "_editions_v_version_contents_article_id_articles_id_fk"
  FOREIGN KEY ("article_id") REFERENCES "articles"("id") ON DELETE SET NULL;

CREATE UNIQUE INDEX "editions_issue_date_idx" ON "editions" USING btree ("issue_date");
CREATE INDEX "editions_cover_idx" ON "editions" USING btree ("cover_id");
CREATE INDEX "editions_replica_pdf_idx" ON "editions" USING btree ("replica_pdf_id");
CREATE INDEX "editions__status_idx" ON "editions" USING btree ("_status");
CREATE INDEX "editions_created_at_idx" ON "editions" USING btree ("created_at");
CREATE INDEX "editions_updated_at_idx" ON "editions" USING btree ("updated_at");

CREATE INDEX "editions_contents_order_idx" ON "editions_contents" USING btree ("_order");
CREATE INDEX "editions_contents_parent_id_idx" ON "editions_contents" USING btree ("_parent_id");
CREATE INDEX "editions_contents_article_idx" ON "editions_contents" USING btree ("article_id");

CREATE INDEX "_editions_v_parent_idx" ON "_editions_v" USING btree ("parent_id");
CREATE INDEX "_editions_v_version_version_cover_idx" ON "_editions_v" USING btree ("version_cover_id");
CREATE INDEX "_editions_v_version_version_replica_pdf_idx" ON "_editions_v" USING btree ("version_replica_pdf_id");
CREATE INDEX "_editions_v_version_version__status_idx" ON "_editions_v" USING btree ("version__status");
CREATE INDEX "_editions_v_version_version_created_at_idx" ON "_editions_v" USING btree ("version_created_at");
CREATE INDEX "_editions_v_version_version_updated_at_idx" ON "_editions_v" USING btree ("version_updated_at");
CREATE INDEX "_editions_v_created_at_idx" ON "_editions_v" USING btree ("created_at");
CREATE INDEX "_editions_v_updated_at_idx" ON "_editions_v" USING btree ("updated_at");

CREATE INDEX "_editions_v_version_contents_order_idx" ON "_editions_v_version_contents" USING btree ("_order");
CREATE INDEX "_editions_v_version_contents_parent_id_idx" ON "_editions_v_version_contents" USING btree ("_parent_id");
CREATE INDEX "_editions_v_version_contents_article_idx" ON "_editions_v_version_contents" USING btree ("article_id");

INSERT INTO payload_migrations (name, batch)
VALUES ('20260926_100000_editions_collection', (SELECT COALESCE(MAX(batch), 0) + 1 FROM payload_migrations));

COMMIT;

-- Verify: the tables exist and are empty.
--
--   SELECT count(*) FROM public.editions;  -- expect 0
