/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Unauthenticated liveness probe for the load balancer.
         *
         *     Deliberately does not touch any database -- a city or platform outage
         *     must not make the load balancer think engine-api itself is down.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/{site}/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** City Health */
        get: operations["city_health_v1__site__health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/{site}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Events
         * @description Accepts one beacon batch and writes it into this city's tables.
         *
         *     Order of checks is deliberate:
         *
         *     1. `Depends(get_city_db)` -- unknown/inactive site -> 404, registry or
         *        city DB unreachable -> 503. Runs before the handler body at all
         *        (FastAPI dependency resolution), so a bad site never even reaches
         *        body parsing.
         *     2. Body-size ceiling, then JSON parse, then schema validation
         *        (`EventsBatchIn`, which itself caps array length at
         *        `MAX_EVENTS_PER_ARRAY`) -- malformed or oversized -> 4xx.
         *     3. CORS origin allowlist (decision C2) -- a disallowed browser
         *        `Origin` -> 403.
         *     4. Rate limit keyed by the batch's `anon_id` -> 429.
         *     5. Write. A `ts` outside the currently provisioned partition window is
         *        a client-data problem, translated to 400 rather than left to
         *        surface as a raw database error.
         *
         *     Every one of the above is a controlled `HTTPException`; nothing here
         *     lets an unexpected exception escape as a bare 500 for these known
         *     failure classes.
         */
        post: operations["post_events_v1__site__events_post"];
        delete?: never;
        /**
         * Preflight Events
         * @description CORS preflight for the `fetch(..., {keepalive})` fallback transport.
         *
         *     The beacon's primary transport, `navigator.sendBeacon`, is always sent
         *     in `no-cors` mode by the browser and never triggers a preflight -- this
         *     handler only matters for the fetch fallback (used when `sendBeacon` is
         *     unavailable) and for manual/XHR testing. No DB touched and no rate
         *     limiting here: a preflight carries no body and no event data, so there
         *     is nothing to write and nothing to key a rate limit on.
         */
        options: operations["preflight_events_v1__site__events_options"];
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CityHealthResponse */
        CityHealthResponse: {
            /** Site */
            site: string;
            /** Status */
            status: string;
            /** Database */
            database: string;
            /** Latency Ms */
            latency_ms: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthzResponse */
        HealthzResponse: {
            /** Status */
            status: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthzResponse"];
                };
            };
        };
    };
    city_health_v1__site__health_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description City site slug, resolved against the `sites` registry. */
                site: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CityHealthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_events_v1__site__events_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description City site slug, resolved against the `sites` registry. */
                site: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preflight_events_v1__site__events_options: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
