// Auto-generated by `payload generate:importmap`. Do not hand-edit — this
// file registers the custom admin UI components Payload's config declares
// (none, currently) so its client bundle can resolve them. Regenerate with
// `npm run generate:importmap` after adding a custom component import.
export const importMap = {}
