import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TYPE "public"."enum_places_cuisine" ADD VALUE 'acehnese' BEFORE 'american';
  ALTER TYPE "public"."enum_places_cuisine" ADD VALUE 'bbq' BEFORE 'betawi';
  ALTER TYPE "public"."enum_places_cuisine" ADD VALUE 'coffee' BEFORE 'european';
  ALTER TYPE "public"."enum_places_cuisine" ADD VALUE 'dessert' BEFORE 'european';
  ALTER TYPE "public"."enum_places_cuisine" ADD VALUE 'fusion' BEFORE 'indian';
  ALTER TYPE "public"."enum_places_cuisine" ADD VALUE 'hotpot' BEFORE 'indian';
  ALTER TYPE "public"."enum_places_cuisine" ADD VALUE 'malaysian' BEFORE 'manadonese';
  ALTER TYPE "public"."enum_places_cuisine" ADD VALUE 'moroccan' BEFORE 'padang';
  ALTER TYPE "public"."enum_places_cuisine" ADD VALUE 'nordic' BEFORE 'padang';
  ALTER TYPE "public"."enum_places_cuisine" ADD VALUE 'portuguese' BEFORE 'seafood';
  ALTER TYPE "public"."enum_places_cuisine" ADD VALUE 'singaporean' BEFORE 'spanish';
  ALTER TYPE "public"."enum_places_cuisine" ADD VALUE 'tea' BEFORE 'thai';
  ALTER TYPE "public"."enum_places_amenities" ADD VALUE 'airport-transfer' BEFORE 'beachfront';
  ALTER TYPE "public"."enum_places_amenities" ADD VALUE 'breakfast-included' BEFORE 'city-view';
  ALTER TYPE "public"."enum_places_amenities" ADD VALUE 'buffet' BEFORE 'city-view';
  ALTER TYPE "public"."enum_places_amenities" ADD VALUE 'butler' BEFORE 'city-view';
  ALTER TYPE "public"."enum_places_amenities" ADD VALUE 'cabanas' BEFORE 'city-view';
  ALTER TYPE "public"."enum_places_amenities" ADD VALUE 'cigar-lounge' BEFORE 'city-view';
  ALTER TYPE "public"."enum_places_amenities" ADD VALUE 'cold-plunge' BEFORE 'coworking-space';
  ALTER TYPE "public"."enum_places_amenities" ADD VALUE 'delivery' BEFORE 'garden';
  ALTER TYPE "public"."enum_places_amenities" ADD VALUE 'dive-centre' BEFORE 'garden';
  ALTER TYPE "public"."enum_places_amenities" ADD VALUE 'free-flow' BEFORE 'garden';
  ALTER TYPE "public"."enum_places_amenities" ADD VALUE 'gluten-free' BEFORE 'gym';
  ALTER TYPE "public"."enum_places_amenities" ADD VALUE 'healthy-menu' BEFORE 'kids-club';
  ALTER TYPE "public"."enum_places_amenities" ADD VALUE 'jungle-view' BEFORE 'kids-club';
  ALTER TYPE "public"."enum_places_amenities" ADD VALUE 'lagoon-pool' BEFORE 'live-music';
  ALTER TYPE "public"."enum_places_amenities" ADD VALUE 'late-night' BEFORE 'outdoor-seating';
  ALTER TYPE "public"."enum_places_amenities" ADD VALUE 'organic' BEFORE 'outdoor-seating';
  ALTER TYPE "public"."enum_places_amenities" ADD VALUE 'private-pool' BEFORE 'rooftop';
  ALTER TYPE "public"."enum_places_amenities" ADD VALUE 'rice-field-view' BEFORE 'rooftop';
  ALTER TYPE "public"."enum_places_amenities" ADD VALUE 'river-view' BEFORE 'rooftop';
  ALTER TYPE "public"."enum_places_amenities" ADD VALUE 'sauna' BEFORE 'spa';
  ALTER TYPE "public"."enum_places_amenities" ADD VALUE 'sports-screening' BEFORE 'valet';
  ALTER TYPE "public"."enum_places_amenities" ADD VALUE 'swim-up-bar' BEFORE 'valet';
  ALTER TYPE "public"."enum_places_amenities" ADD VALUE 'wine-cellar';
  ALTER TYPE "public"."enum_places_vibe" ADD VALUE 'authentic' BEFORE 'casual';
  ALTER TYPE "public"."enum_places_vibe" ADD VALUE 'chic' BEFORE 'classic';
  ALTER TYPE "public"."enum_places_vibe" ADD VALUE 'edgy' BEFORE 'hidden-gem';
  ALTER TYPE "public"."enum_places_vibe" ADD VALUE 'exclusive' BEFORE 'hidden-gem';
  ALTER TYPE "public"."enum_places_vibe" ADD VALUE 'family-friendly' BEFORE 'hidden-gem';
  ALTER TYPE "public"."enum_places_vibe" ADD VALUE 'glamorous' BEFORE 'hidden-gem';
  ALTER TYPE "public"."enum_places_vibe" ADD VALUE 'modern' BEFORE 'party';
  ALTER TYPE "public"."enum_places_vibe" ADD VALUE 'nostalgic' BEFORE 'party';
  ALTER TYPE "public"."enum_places_vibe" ADD VALUE 'quirky' BEFORE 'romantic';
  ALTER TYPE "public"."enum_places_vibe" ADD VALUE 'rustic' BEFORE 'scenic';
  ALTER TYPE "public"."enum_places_vibe" ADD VALUE 'tropical';
  ALTER TYPE "public"."enum_places_vibe" ADD VALUE 'wholesome';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'aceh' BEFORE 'alam-sutera';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'africa' BEFORE 'alam-sutera';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'australia' BEFORE 'bali';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'bangli' BEFORE 'banyuwangi';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'bedugul' BEFORE 'bekasi';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'cambodia' BEFORE 'candidasa';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'casablanca' BEFORE 'central-bali';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'cengkareng' BEFORE 'central-bali';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'china' BEFORE 'cibubur';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'cilandak' BEFORE 'cipete';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'cirebon' BEFORE 'denpasar';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'europe' BEFORE 'gading-serpong';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'gatot-subroto' BEFORE 'glodok';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'gianyar' BEFORE 'glodok';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'hong-kong' BEFORE 'indonesia';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'india' BEFORE 'indonesia';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'japan' BEFORE 'jimbaran';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'jatiluwih' BEFORE 'jimbaran';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'java' BEFORE 'jimbaran';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'kalimantan' BEFORE 'kebon-jeruk';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'kebayoran-baru' BEFORE 'kebon-jeruk';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'kebon-sirih' BEFORE 'kelapa-gading';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'kemayoran' BEFORE 'kerobokan';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'kepulauan-seribu' BEFORE 'kerobokan';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'kintamani' BEFORE 'komodo';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'lampung' BEFORE 'legian';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'malaysia' BEFORE 'manado';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'maldives' BEFORE 'manado';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'maluku' BEFORE 'manado';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'mengwi' BEFORE 'menteng';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'middle-east' BEFORE 'north-bali';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'new-zealand' BEFORE 'north-bali';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'nusa-lembongan' BEFORE 'nusa-penida';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'nusa-tenggara' BEFORE 'pasar-baru';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'padang' BEFORE 'pasar-baru';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'palembang' BEFORE 'pasar-baru';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'philippines' BEFORE 'pik';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'riau-islands' BEFORE 'sanur';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'singapore' BEFORE 'solo';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'south-korea' BEFORE 'sudirman';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'sri-lanka' BEFORE 'sudirman';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'sulawesi' BEFORE 'sumba';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'sumatra' BEFORE 'sumba';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'tabanan' BEFORE 'tangerang';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'taiwan' BEFORE 'tangerang';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'tanah-abang' BEFORE 'tangerang';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'tanah-lot' BEFORE 'tangerang';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'thailand' BEFORE 'thamrin';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'tmii' BEFORE 'toraja';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'turkey' BEFORE 'ubud';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'uae' BEFORE 'west-jakarta';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'usa' BEFORE 'west-jakarta';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'vietnam' BEFORE 'west-jakarta';
  ALTER TYPE "public"."enum_places_area_term" ADD VALUE 'west-bali' BEFORE 'west-jakarta';
  ALTER TYPE "public"."enum_places_subtype" ADD VALUE 'bookshop' BEFORE 'boutique';
  ALTER TYPE "public"."enum_places_subtype" ADD VALUE 'place-of-worship' BEFORE 'city-guide';
  ALTER TYPE "public"."enum_places_subtype" ADD VALUE 'cinema' BEFORE 'city-guide';
  ALTER TYPE "public"."enum_places_subtype" ADD VALUE 'dessert-shop' BEFORE 'education';
  ALTER TYPE "public"."enum_places_subtype" ADD VALUE 'farm' BEFORE 'festival';
  ALTER TYPE "public"."enum_places_subtype" ADD VALUE 'karaoke' BEFORE 'lifestyle';
  ALTER TYPE "public"."enum_places_subtype" ADD VALUE 'nature' BEFORE 'news';
  ALTER TYPE "public"."enum_places_subtype" ADD VALUE 'temple' BEFORE 'tour';
  ALTER TYPE "public"."enum_places_subtype" ADD VALUE 'theatre' BEFORE 'tour';
  ALTER TYPE "public"."enum_places_subtype" ADD VALUE 'winery-distillery' BEFORE 'workshop';
  ALTER TYPE "public"."enum_places_subtype" ADD VALUE 'zoo';
  ALTER TYPE "public"."enum__places_v_version_cuisine" ADD VALUE 'acehnese' BEFORE 'american';
  ALTER TYPE "public"."enum__places_v_version_cuisine" ADD VALUE 'bbq' BEFORE 'betawi';
  ALTER TYPE "public"."enum__places_v_version_cuisine" ADD VALUE 'coffee' BEFORE 'european';
  ALTER TYPE "public"."enum__places_v_version_cuisine" ADD VALUE 'dessert' BEFORE 'european';
  ALTER TYPE "public"."enum__places_v_version_cuisine" ADD VALUE 'fusion' BEFORE 'indian';
  ALTER TYPE "public"."enum__places_v_version_cuisine" ADD VALUE 'hotpot' BEFORE 'indian';
  ALTER TYPE "public"."enum__places_v_version_cuisine" ADD VALUE 'malaysian' BEFORE 'manadonese';
  ALTER TYPE "public"."enum__places_v_version_cuisine" ADD VALUE 'moroccan' BEFORE 'padang';
  ALTER TYPE "public"."enum__places_v_version_cuisine" ADD VALUE 'nordic' BEFORE 'padang';
  ALTER TYPE "public"."enum__places_v_version_cuisine" ADD VALUE 'portuguese' BEFORE 'seafood';
  ALTER TYPE "public"."enum__places_v_version_cuisine" ADD VALUE 'singaporean' BEFORE 'spanish';
  ALTER TYPE "public"."enum__places_v_version_cuisine" ADD VALUE 'tea' BEFORE 'thai';
  ALTER TYPE "public"."enum__places_v_version_amenities" ADD VALUE 'airport-transfer' BEFORE 'beachfront';
  ALTER TYPE "public"."enum__places_v_version_amenities" ADD VALUE 'breakfast-included' BEFORE 'city-view';
  ALTER TYPE "public"."enum__places_v_version_amenities" ADD VALUE 'buffet' BEFORE 'city-view';
  ALTER TYPE "public"."enum__places_v_version_amenities" ADD VALUE 'butler' BEFORE 'city-view';
  ALTER TYPE "public"."enum__places_v_version_amenities" ADD VALUE 'cabanas' BEFORE 'city-view';
  ALTER TYPE "public"."enum__places_v_version_amenities" ADD VALUE 'cigar-lounge' BEFORE 'city-view';
  ALTER TYPE "public"."enum__places_v_version_amenities" ADD VALUE 'cold-plunge' BEFORE 'coworking-space';
  ALTER TYPE "public"."enum__places_v_version_amenities" ADD VALUE 'delivery' BEFORE 'garden';
  ALTER TYPE "public"."enum__places_v_version_amenities" ADD VALUE 'dive-centre' BEFORE 'garden';
  ALTER TYPE "public"."enum__places_v_version_amenities" ADD VALUE 'free-flow' BEFORE 'garden';
  ALTER TYPE "public"."enum__places_v_version_amenities" ADD VALUE 'gluten-free' BEFORE 'gym';
  ALTER TYPE "public"."enum__places_v_version_amenities" ADD VALUE 'healthy-menu' BEFORE 'kids-club';
  ALTER TYPE "public"."enum__places_v_version_amenities" ADD VALUE 'jungle-view' BEFORE 'kids-club';
  ALTER TYPE "public"."enum__places_v_version_amenities" ADD VALUE 'lagoon-pool' BEFORE 'live-music';
  ALTER TYPE "public"."enum__places_v_version_amenities" ADD VALUE 'late-night' BEFORE 'outdoor-seating';
  ALTER TYPE "public"."enum__places_v_version_amenities" ADD VALUE 'organic' BEFORE 'outdoor-seating';
  ALTER TYPE "public"."enum__places_v_version_amenities" ADD VALUE 'private-pool' BEFORE 'rooftop';
  ALTER TYPE "public"."enum__places_v_version_amenities" ADD VALUE 'rice-field-view' BEFORE 'rooftop';
  ALTER TYPE "public"."enum__places_v_version_amenities" ADD VALUE 'river-view' BEFORE 'rooftop';
  ALTER TYPE "public"."enum__places_v_version_amenities" ADD VALUE 'sauna' BEFORE 'spa';
  ALTER TYPE "public"."enum__places_v_version_amenities" ADD VALUE 'sports-screening' BEFORE 'valet';
  ALTER TYPE "public"."enum__places_v_version_amenities" ADD VALUE 'swim-up-bar' BEFORE 'valet';
  ALTER TYPE "public"."enum__places_v_version_amenities" ADD VALUE 'wine-cellar';
  ALTER TYPE "public"."enum__places_v_version_vibe" ADD VALUE 'authentic' BEFORE 'casual';
  ALTER TYPE "public"."enum__places_v_version_vibe" ADD VALUE 'chic' BEFORE 'classic';
  ALTER TYPE "public"."enum__places_v_version_vibe" ADD VALUE 'edgy' BEFORE 'hidden-gem';
  ALTER TYPE "public"."enum__places_v_version_vibe" ADD VALUE 'exclusive' BEFORE 'hidden-gem';
  ALTER TYPE "public"."enum__places_v_version_vibe" ADD VALUE 'family-friendly' BEFORE 'hidden-gem';
  ALTER TYPE "public"."enum__places_v_version_vibe" ADD VALUE 'glamorous' BEFORE 'hidden-gem';
  ALTER TYPE "public"."enum__places_v_version_vibe" ADD VALUE 'modern' BEFORE 'party';
  ALTER TYPE "public"."enum__places_v_version_vibe" ADD VALUE 'nostalgic' BEFORE 'party';
  ALTER TYPE "public"."enum__places_v_version_vibe" ADD VALUE 'quirky' BEFORE 'romantic';
  ALTER TYPE "public"."enum__places_v_version_vibe" ADD VALUE 'rustic' BEFORE 'scenic';
  ALTER TYPE "public"."enum__places_v_version_vibe" ADD VALUE 'tropical';
  ALTER TYPE "public"."enum__places_v_version_vibe" ADD VALUE 'wholesome';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'aceh' BEFORE 'alam-sutera';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'africa' BEFORE 'alam-sutera';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'australia' BEFORE 'bali';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'bangli' BEFORE 'banyuwangi';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'bedugul' BEFORE 'bekasi';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'cambodia' BEFORE 'candidasa';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'casablanca' BEFORE 'central-bali';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'cengkareng' BEFORE 'central-bali';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'china' BEFORE 'cibubur';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'cilandak' BEFORE 'cipete';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'cirebon' BEFORE 'denpasar';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'europe' BEFORE 'gading-serpong';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'gatot-subroto' BEFORE 'glodok';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'gianyar' BEFORE 'glodok';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'hong-kong' BEFORE 'indonesia';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'india' BEFORE 'indonesia';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'japan' BEFORE 'jimbaran';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'jatiluwih' BEFORE 'jimbaran';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'java' BEFORE 'jimbaran';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'kalimantan' BEFORE 'kebon-jeruk';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'kebayoran-baru' BEFORE 'kebon-jeruk';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'kebon-sirih' BEFORE 'kelapa-gading';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'kemayoran' BEFORE 'kerobokan';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'kepulauan-seribu' BEFORE 'kerobokan';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'kintamani' BEFORE 'komodo';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'lampung' BEFORE 'legian';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'malaysia' BEFORE 'manado';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'maldives' BEFORE 'manado';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'maluku' BEFORE 'manado';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'mengwi' BEFORE 'menteng';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'middle-east' BEFORE 'north-bali';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'new-zealand' BEFORE 'north-bali';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'nusa-lembongan' BEFORE 'nusa-penida';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'nusa-tenggara' BEFORE 'pasar-baru';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'padang' BEFORE 'pasar-baru';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'palembang' BEFORE 'pasar-baru';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'philippines' BEFORE 'pik';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'riau-islands' BEFORE 'sanur';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'singapore' BEFORE 'solo';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'south-korea' BEFORE 'sudirman';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'sri-lanka' BEFORE 'sudirman';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'sulawesi' BEFORE 'sumba';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'sumatra' BEFORE 'sumba';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'tabanan' BEFORE 'tangerang';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'taiwan' BEFORE 'tangerang';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'tanah-abang' BEFORE 'tangerang';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'tanah-lot' BEFORE 'tangerang';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'thailand' BEFORE 'thamrin';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'tmii' BEFORE 'toraja';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'turkey' BEFORE 'ubud';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'uae' BEFORE 'west-jakarta';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'usa' BEFORE 'west-jakarta';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'vietnam' BEFORE 'west-jakarta';
  ALTER TYPE "public"."enum__places_v_version_area_term" ADD VALUE 'west-bali' BEFORE 'west-jakarta';
  ALTER TYPE "public"."enum__places_v_version_subtype" ADD VALUE 'bookshop' BEFORE 'boutique';
  ALTER TYPE "public"."enum__places_v_version_subtype" ADD VALUE 'place-of-worship' BEFORE 'city-guide';
  ALTER TYPE "public"."enum__places_v_version_subtype" ADD VALUE 'cinema' BEFORE 'city-guide';
  ALTER TYPE "public"."enum__places_v_version_subtype" ADD VALUE 'dessert-shop' BEFORE 'education';
  ALTER TYPE "public"."enum__places_v_version_subtype" ADD VALUE 'farm' BEFORE 'festival';
  ALTER TYPE "public"."enum__places_v_version_subtype" ADD VALUE 'karaoke' BEFORE 'lifestyle';
  ALTER TYPE "public"."enum__places_v_version_subtype" ADD VALUE 'nature' BEFORE 'news';
  ALTER TYPE "public"."enum__places_v_version_subtype" ADD VALUE 'temple' BEFORE 'tour';
  ALTER TYPE "public"."enum__places_v_version_subtype" ADD VALUE 'theatre' BEFORE 'tour';
  ALTER TYPE "public"."enum__places_v_version_subtype" ADD VALUE 'winery-distillery' BEFORE 'workshop';
  ALTER TYPE "public"."enum__places_v_version_subtype" ADD VALUE 'zoo';`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "places_cuisine" ALTER COLUMN "value" SET DATA TYPE text;
  DROP TYPE "public"."enum_places_cuisine";
  CREATE TYPE "public"."enum_places_cuisine" AS ENUM('american', 'asian-fusion', 'balinese', 'betawi', 'chinese', 'european', 'french', 'indian', 'indonesian', 'italian', 'japanese', 'javanese', 'korean', 'latin-american', 'manadonese', 'mediterranean', 'mexican', 'middle-eastern', 'padang', 'peranakan', 'seafood', 'spanish', 'steakhouse', 'sundanese', 'thai', 'vietnamese', 'western');
  ALTER TABLE "places_cuisine" ALTER COLUMN "value" SET DATA TYPE "public"."enum_places_cuisine" USING "value"::"public"."enum_places_cuisine";
  ALTER TABLE "places_amenities" ALTER COLUMN "value" SET DATA TYPE text;
  DROP TYPE "public"."enum_places_amenities";
  CREATE TYPE "public"."enum_places_amenities" AS ENUM('beachfront', 'city-view', 'coworking-space', 'garden', 'gym', 'halal-certified', 'kids-club', 'live-music', 'ocean-view', 'outdoor-seating', 'parking', 'pet-friendly', 'pool', 'private-dining', 'rooftop', 'spa', 'valet', 'vegan-options', 'vegetarian-friendly', 'wheelchair-accessible', 'wifi');
  ALTER TABLE "places_amenities" ALTER COLUMN "value" SET DATA TYPE "public"."enum_places_amenities" USING "value"::"public"."enum_places_amenities";
  ALTER TABLE "places_vibe" ALTER COLUMN "value" SET DATA TYPE text;
  DROP TYPE "public"."enum_places_vibe";
  CREATE TYPE "public"."enum_places_vibe" AS ENUM('artsy', 'casual', 'classic', 'cozy', 'hidden-gem', 'instagrammable', 'laid-back', 'lively', 'luxury', 'party', 'romantic', 'scenic', 'serene', 'trendy');
  ALTER TABLE "places_vibe" ALTER COLUMN "value" SET DATA TYPE "public"."enum_places_vibe" USING "value"::"public"."enum_places_vibe";
  ALTER TABLE "places" ALTER COLUMN "area_term" SET DATA TYPE text;
  DROP TYPE "public"."enum_places_area_term";
  CREATE TYPE "public"."enum_places_area_term" AS ENUM('alam-sutera', 'amed', 'ancol', 'bali', 'bandung', 'banyuwangi', 'bekasi', 'belitung', 'bintan', 'bintaro', 'blok-m', 'bogor', 'bsd', 'candidasa', 'canggu', 'central-bali', 'central-jakarta', 'cibubur', 'cikini', 'cipete', 'denpasar', 'depok', 'east-bali', 'east-jakarta', 'other', 'gading-serpong', 'gambir', 'glodok', 'greater-jakarta', 'gunawarman', 'indonesia', 'international', 'jakarta', 'jimbaran', 'kebon-jeruk', 'kelapa-gading', 'kemang', 'kerobokan', 'komodo', 'kota-tua', 'kuningan', 'kuta', 'lake-toba', 'legian', 'lombok', 'lovina', 'makassar', 'malang', 'manado', 'medan', 'menteng', 'north-bali', 'north-jakarta', 'nusa-dua', 'nusa-penida', 'pasar-baru', 'pererenan', 'pik', 'pondok-indah', 'puncak', 'puri-indah', 'raja-ampat', 'rawamangun', 'sanur', 'scbd', 'semarang', 'seminyak', 'senayan', 'senopati', 'sentul', 'sidemen', 'solo', 'south-bali', 'south-jakarta', 'sudirman', 'sumba', 'surabaya', 'tangerang', 'tebet', 'thamrin', 'toraja', 'ubud', 'uluwatu', 'west-jakarta', 'yogyakarta');
  ALTER TABLE "places" ALTER COLUMN "area_term" SET DATA TYPE "public"."enum_places_area_term" USING "area_term"::"public"."enum_places_area_term";
  ALTER TABLE "places" ALTER COLUMN "subtype" SET DATA TYPE text;
  DROP TYPE "public"."enum_places_subtype";
  CREATE TYPE "public"."enum_places_subtype" AS ENUM('adventure', 'artisan', 'attraction', 'bakery', 'bar', 'beach-club', 'boutique', 'boutique-hotel', 'business', 'cafe', 'city-guide', 'clinic', 'cocktail-bar', 'community', 'concert', 'conference', 'culture', 'education', 'exhibition', 'festival', 'fine-dining', 'food-court', 'gallery', 'glamping', 'gym', 'heritage', 'hotel', 'lifestyle', 'mall', 'market', 'museum', 'news', 'nightclub', 'opinion', 'people', 'performance', 'pop-up', 'pub', 'resort', 'restaurant', 'retreat', 'rooftop-bar', 'salon', 'screening', 'serviced-apartment', 'spa', 'sports', 'sports-activity', 'street-food', 'tour', 'villa', 'watersports', 'wine-bar', 'workshop', 'yoga');
  ALTER TABLE "places" ALTER COLUMN "subtype" SET DATA TYPE "public"."enum_places_subtype" USING "subtype"::"public"."enum_places_subtype";
  ALTER TABLE "_places_v_version_cuisine" ALTER COLUMN "value" SET DATA TYPE text;
  DROP TYPE "public"."enum__places_v_version_cuisine";
  CREATE TYPE "public"."enum__places_v_version_cuisine" AS ENUM('american', 'asian-fusion', 'balinese', 'betawi', 'chinese', 'european', 'french', 'indian', 'indonesian', 'italian', 'japanese', 'javanese', 'korean', 'latin-american', 'manadonese', 'mediterranean', 'mexican', 'middle-eastern', 'padang', 'peranakan', 'seafood', 'spanish', 'steakhouse', 'sundanese', 'thai', 'vietnamese', 'western');
  ALTER TABLE "_places_v_version_cuisine" ALTER COLUMN "value" SET DATA TYPE "public"."enum__places_v_version_cuisine" USING "value"::"public"."enum__places_v_version_cuisine";
  ALTER TABLE "_places_v_version_amenities" ALTER COLUMN "value" SET DATA TYPE text;
  DROP TYPE "public"."enum__places_v_version_amenities";
  CREATE TYPE "public"."enum__places_v_version_amenities" AS ENUM('beachfront', 'city-view', 'coworking-space', 'garden', 'gym', 'halal-certified', 'kids-club', 'live-music', 'ocean-view', 'outdoor-seating', 'parking', 'pet-friendly', 'pool', 'private-dining', 'rooftop', 'spa', 'valet', 'vegan-options', 'vegetarian-friendly', 'wheelchair-accessible', 'wifi');
  ALTER TABLE "_places_v_version_amenities" ALTER COLUMN "value" SET DATA TYPE "public"."enum__places_v_version_amenities" USING "value"::"public"."enum__places_v_version_amenities";
  ALTER TABLE "_places_v_version_vibe" ALTER COLUMN "value" SET DATA TYPE text;
  DROP TYPE "public"."enum__places_v_version_vibe";
  CREATE TYPE "public"."enum__places_v_version_vibe" AS ENUM('artsy', 'casual', 'classic', 'cozy', 'hidden-gem', 'instagrammable', 'laid-back', 'lively', 'luxury', 'party', 'romantic', 'scenic', 'serene', 'trendy');
  ALTER TABLE "_places_v_version_vibe" ALTER COLUMN "value" SET DATA TYPE "public"."enum__places_v_version_vibe" USING "value"::"public"."enum__places_v_version_vibe";
  ALTER TABLE "_places_v" ALTER COLUMN "version_area_term" SET DATA TYPE text;
  DROP TYPE "public"."enum__places_v_version_area_term";
  CREATE TYPE "public"."enum__places_v_version_area_term" AS ENUM('alam-sutera', 'amed', 'ancol', 'bali', 'bandung', 'banyuwangi', 'bekasi', 'belitung', 'bintan', 'bintaro', 'blok-m', 'bogor', 'bsd', 'candidasa', 'canggu', 'central-bali', 'central-jakarta', 'cibubur', 'cikini', 'cipete', 'denpasar', 'depok', 'east-bali', 'east-jakarta', 'other', 'gading-serpong', 'gambir', 'glodok', 'greater-jakarta', 'gunawarman', 'indonesia', 'international', 'jakarta', 'jimbaran', 'kebon-jeruk', 'kelapa-gading', 'kemang', 'kerobokan', 'komodo', 'kota-tua', 'kuningan', 'kuta', 'lake-toba', 'legian', 'lombok', 'lovina', 'makassar', 'malang', 'manado', 'medan', 'menteng', 'north-bali', 'north-jakarta', 'nusa-dua', 'nusa-penida', 'pasar-baru', 'pererenan', 'pik', 'pondok-indah', 'puncak', 'puri-indah', 'raja-ampat', 'rawamangun', 'sanur', 'scbd', 'semarang', 'seminyak', 'senayan', 'senopati', 'sentul', 'sidemen', 'solo', 'south-bali', 'south-jakarta', 'sudirman', 'sumba', 'surabaya', 'tangerang', 'tebet', 'thamrin', 'toraja', 'ubud', 'uluwatu', 'west-jakarta', 'yogyakarta');
  ALTER TABLE "_places_v" ALTER COLUMN "version_area_term" SET DATA TYPE "public"."enum__places_v_version_area_term" USING "version_area_term"::"public"."enum__places_v_version_area_term";
  ALTER TABLE "_places_v" ALTER COLUMN "version_subtype" SET DATA TYPE text;
  DROP TYPE "public"."enum__places_v_version_subtype";
  CREATE TYPE "public"."enum__places_v_version_subtype" AS ENUM('adventure', 'artisan', 'attraction', 'bakery', 'bar', 'beach-club', 'boutique', 'boutique-hotel', 'business', 'cafe', 'city-guide', 'clinic', 'cocktail-bar', 'community', 'concert', 'conference', 'culture', 'education', 'exhibition', 'festival', 'fine-dining', 'food-court', 'gallery', 'glamping', 'gym', 'heritage', 'hotel', 'lifestyle', 'mall', 'market', 'museum', 'news', 'nightclub', 'opinion', 'people', 'performance', 'pop-up', 'pub', 'resort', 'restaurant', 'retreat', 'rooftop-bar', 'salon', 'screening', 'serviced-apartment', 'spa', 'sports', 'sports-activity', 'street-food', 'tour', 'villa', 'watersports', 'wine-bar', 'workshop', 'yoga');
  ALTER TABLE "_places_v" ALTER COLUMN "version_subtype" SET DATA TYPE "public"."enum__places_v_version_subtype" USING "version_subtype"::"public"."enum__places_v_version_subtype";`)
}
