"""Generates the SQL that proves the ARCHITECTURE.md §15 contract this
package must honour at request time downstream: **"nearby radius uses
PostGIS `ST_DWithin`, never Google at request time."**

This module has no database dependency of its own (no `psycopg` import,
no connection) — it only produces a self-contained SQL script. That
keeps `now-geocode` a pure file-in/file-out tool (its actual job) while
still making the PostGIS claim checkable with real output: pipe the
generated script into any Postgres that has PostGIS enabled, e.g.

    now-geocode postgis-sql geocoded_places.jsonl | \\
        docker exec -i now-postgres psql -U now -d now_test

Deliberately uses `CREATE TEMP TABLE ... ON COMMIT DROP` in its own
transaction — the demo data never touches a persistent table (this
package does not own the database; E2.3/E1.8 do) and leaves nothing
behind once the session ends.
"""

from __future__ import annotations

from now_geocode.models import GeocodedPlace, Status


def _sql_literal(value: str | None) -> str:
    if value is None:
        return "NULL"
    return "'" + value.replace("'", "''") + "'"


def render_st_dwithin_demo_sql(
    places: list[GeocodedPlace], *, radius_m: float = 2000.0, limit_pairs: int = 25
) -> str:
    usable = [
        p
        for p in places
        if p.lat is not None
        and p.lng is not None
        and p.status in (Status.RESOLVED, Status.RESOLVED_SYNTHETIC)
    ]

    lines: list[str] = []
    lines.append("-- E2.5 PostGIS ST_DWithin demonstration — generated by now-geocode.")
    lines.append("-- Loads resolved coordinates into a session-local TEMP TABLE (auto-dropped")
    lines.append("-- on commit), never a persistent table — this package does not own the DB.")
    lines.append("BEGIN;")
    lines.append("")
    lines.append("CREATE TEMP TABLE geocode_demo_points (")
    lines.append("    place_key text PRIMARY KEY,")
    lines.append("    name text NOT NULL,")
    lines.append("    area_term text,")
    lines.append("    source text NOT NULL,")
    lines.append("    geo geography(Point,4326) NOT NULL")
    lines.append(") ON COMMIT DROP;")
    lines.append("")

    if not usable:
        lines.append("-- No resolved coordinates were available to demonstrate with.")
        lines.append("ROLLBACK;")
        return "\n".join(lines) + "\n"

    lines.append("INSERT INTO geocode_demo_points (place_key, name, area_term, source, geo) VALUES")
    value_rows = []
    for p in usable:
        value_rows.append(
            "  ("
            + ", ".join(
                [
                    _sql_literal(p.place_key),
                    _sql_literal(p.name),
                    _sql_literal(p.area_term),
                    _sql_literal(p.source.value),
                    f"ST_SetSRID(ST_MakePoint({p.lng}, {p.lat}), 4326)::geography",
                ]
            )
            + ")"
        )
    lines.append(",\n".join(value_rows) + ";")
    lines.append("")
    lines.append(f"-- Row 2 proof: distinct resolved places within {radius_m:.0f}m of each other,")
    lines.append("-- computed entirely in PostGIS — no external geocoding call at query time.")
    lines.append("SELECT")
    lines.append("    a.name AS place,")
    lines.append("    b.name AS nearby_within_radius,")
    lines.append("    a.area_term,")
    lines.append("    round(ST_Distance(a.geo, b.geo)::numeric, 1) AS meters")
    lines.append("FROM geocode_demo_points a")
    lines.append("JOIN geocode_demo_points b")
    lines.append(f"  ON a.place_key < b.place_key AND ST_DWithin(a.geo, b.geo, {radius_m})")
    lines.append("ORDER BY meters")
    lines.append(f"LIMIT {limit_pairs};")
    lines.append("")
    lines.append(f"SELECT count(*) AS points_loaded FROM geocode_demo_points;")
    lines.append("")
    lines.append("COMMIT;")
    return "\n".join(lines) + "\n"
