"""Candidate vocabulary NOT in the seed, per facet -- what we go looking for
in the corpus so the "missing terms" direction of the vocabulary check is
not limited to what the seed already knows. Curated, deliberately broad;
a candidate only surfaces in the report when the archive actually uses it.

Each entry: canonical label -> list of surface forms (case-insensitive,
word-boundary matched). Labels that already exist in the seed are filtered
out at runtime, so this list may safely overlap with it.
"""
from __future__ import annotations

CANDIDATES: dict[str, dict[str, list[str]]] = {
    "cuisine": {
        "Singaporean": ["Singaporean"], "Malaysian": ["Malaysian"], "Filipino": ["Filipino"], "Australian": ["Australian cuisine", "modern Australian"],
        "British": ["British"], "German": ["German"], "Dutch": ["Dutch cuisine", "Dutch food"], "Swiss": ["Swiss"], "Nordic": ["Nordic", "Scandinavian"],
        "Portuguese": ["Portuguese"], "Greek": ["Greek"], "Turkish": ["Turkish"], "Lebanese": ["Lebanese"], "Moroccan": ["Moroccan"], "Persian": ["Persian"],
        "Peruvian": ["Peruvian", "Nikkei"], "Brazilian": ["Brazilian", "churrascaria", "churrasco"], "Argentinian": ["Argentinian", "Argentine", "asado"],
        "Cantonese": ["Cantonese"], "Sichuan": ["Sichuan", "Szechuan"], "Hokkien": ["Hokkien"], "Taiwanese": ["Taiwanese"], "Hong Kong": ["Hong Kong-style", "HK-style"],
        "Dim sum": ["dim sum"], "Hotpot": ["hotpot", "hot pot", "shabu-shabu", "shabu"], "Sushi": ["sushi"], "Ramen": ["ramen"], "Izakaya": ["izakaya"], "Yakitori": ["yakitori"], "Teppanyaki": ["teppanyaki"],
        "Pizza": ["pizza", "pizzeria"], "Pasta": ["pasta"], "Burgers": ["burgers", "burger"], "Steak": ["steak", "steakhouse", "wagyu"], "BBQ": ["barbecue", "BBQ", "smokehouse"],
        "Tapas": ["tapas"], "Vegan": ["vegan"], "Vegetarian": ["vegetarian"], "Plant-based": ["plant-based"], "Raw food": ["raw food"], "Gluten-free": ["gluten-free"],
        "Healthy": ["healthy food", "health food", "clean eating", "superfood"], "Organic": ["organic"], "Farm-to-table": ["farm-to-table", "farm to table"],
        "Seafood": ["seafood"], "Fusion": ["fusion"], "Pan-Asian": ["pan-Asian", "modern Asian", "Asian fusion"], "Nusantara": ["Nusantara"], "Indonesian": ["Indonesian cuisine", "Indonesian food"],
        "Balinese": ["Balinese cuisine", "Balinese food", "babi guling"], "Padang": ["Padang", "Minang"], "Sundanese": ["Sundanese", "Sunda"], "Javanese": ["Javanese cuisine", "Javanese food"], "Betawi": ["Betawi"],
        "Manadonese": ["Manado", "Manadonese", "Minahasa"], "Peranakan": ["Peranakan", "Nyonya"], "Acehnese": ["Acehnese", "Aceh"], "Makassar": ["Makassar cuisine", "coto Makassar"], "Balinese warung": ["warung"],
        "Coffee": ["coffee", "kopi", "specialty coffee", "espresso"], "Tea": ["tea house", "teahouse", "afternoon tea", "high tea"], "Dessert": ["dessert", "gelato", "ice cream", "patisserie", "pastry"],
        "Bakery": ["bakery", "sourdough", "croissant"], "Brunch": ["brunch"], "Street food": ["street food", "kaki lima", "hawker"], "Fine dining": ["fine dining", "tasting menu", "degustation", "omakase", "Michelin"],
        "Halal": ["halal"], "Korean BBQ": ["Korean BBQ", "KBBQ", "samgyupsal"], "Thai": ["Thai"], "Vietnamese": ["Vietnamese", "pho", "banh mi"], "Indian": ["Indian", "curry house"], "Mexican": ["Mexican", "taco", "tacos", "taqueria"],
        "Italian": ["Italian"], "French": ["French", "bistro", "brasserie"], "Spanish": ["Spanish"], "Mediterranean": ["Mediterranean"], "Middle Eastern": ["Middle Eastern", "Arabic", "Arab"], "Japanese": ["Japanese"], "Chinese": ["Chinese"], "Korean": ["Korean"], "American": ["American"], "Western": ["Western food", "Western cuisine"],
    },
    "location_jakarta": {
        "Senopati": ["Senopati"], "SCBD": ["SCBD", "Sudirman Central Business District"], "Kemang": ["Kemang"], "Blok M": ["Blok M", "Melawai"], "Pondok Indah": ["Pondok Indah"], "Senayan": ["Senayan", "GBK"], "Cipete": ["Cipete"],
        "Kuningan": ["Kuningan", "Mega Kuningan", "Setiabudi", "Rasuna Said"], "Gunawarman / Dharmawangsa": ["Gunawarman", "Dharmawangsa", "Wijaya", "Wolter Monginsidi"], "Tebet": ["Tebet"], "Kebayoran Baru": ["Kebayoran Baru", "Kebayoran"],
        "Cilandak": ["Cilandak", "TB Simatupang", "Simatupang", "Fatmawati"], "Pejaten": ["Pejaten"], "Kalibata": ["Kalibata"], "Gatot Subroto": ["Gatot Subroto"], "Casablanca": ["Casablanca", "Kota Kasablanka"], "Antasari": ["Antasari"],
        "Menteng": ["Menteng"], "Thamrin": ["Thamrin", "Bundaran HI", "Grand Indonesia", "Plaza Indonesia"], "Sudirman": ["Sudirman", "Dukuh Atas", "Karet"], "Gambir": ["Gambir", "Monas", "Merdeka Square"], "Cikini": ["Cikini", "Taman Ismail Marzuki", "TIM"],
        "Pasar Baru": ["Pasar Baru", "Passer Baroe"], "Kemayoran": ["Kemayoran", "JIExpo"], "Kebon Sirih": ["Kebon Sirih", "Sabang"], "Tanah Abang": ["Tanah Abang"], "Senen": ["Senen"], "Cempaka Putih": ["Cempaka Putih"], "Sunter": ["Sunter"],
        "PIK": ["PIK", "Pantai Indah Kapuk"], "Kelapa Gading": ["Kelapa Gading"], "Ancol": ["Ancol", "Dufan"], "Pluit": ["Pluit"], "Sunda Kelapa": ["Sunda Kelapa"], "Kota Tua": ["Kota Tua", "Old Town", "Old Batavia", "Fatahillah"], "Glodok": ["Glodok", "Chinatown", "Petak Sembilan"],
        "Puri Indah": ["Puri Indah", "Puri Kembangan"], "Kebon Jeruk": ["Kebon Jeruk"], "Slipi": ["Slipi"], "Tomang": ["Tomang"], "Grogol": ["Grogol"], "Cengkareng": ["Cengkareng", "Soekarno-Hatta"],
        "Cibubur": ["Cibubur"], "Rawamangun": ["Rawamangun", "Pulomas"], "Jatinegara": ["Jatinegara"], "Condet": ["Condet"], "TMII": ["Taman Mini", "TMII"], "Cawang": ["Cawang"], "Mampang": ["Mampang"],
        "BSD": ["BSD", "Bumi Serpong Damai", "Serpong"], "Tangerang": ["Tangerang"], "Bekasi": ["Bekasi"], "Bogor": ["Bogor"], "Depok": ["Depok"], "Bintaro": ["Bintaro"], "Alam Sutera": ["Alam Sutera"], "Gading Serpong": ["Gading Serpong", "Summarecon Serpong"],
        "Sentul": ["Sentul"], "Puncak": ["Puncak", "Cisarua", "Cipanas"], "Karawaci": ["Karawaci", "Lippo Village"], "Cikarang": ["Cikarang"], "Kepulauan Seribu": ["Thousand Islands", "Kepulauan Seribu", "Pulau Seribu"],
        "South Jakarta": ["South Jakarta", "Jakarta Selatan", "Jaksel"], "Central Jakarta": ["Central Jakarta", "Jakarta Pusat"], "North Jakarta": ["North Jakarta", "Jakarta Utara"], "West Jakarta": ["West Jakarta", "Jakarta Barat"], "East Jakarta": ["East Jakarta", "Jakarta Timur"],
    },
    "location_bali": {
        "Seminyak": ["Seminyak", "Petitenget", "Oberoi", "Kayu Aya"], "Canggu": ["Canggu", "Batu Bolong", "Berawa", "Echo Beach"], "Kuta": ["Kuta", "Tuban"], "Legian": ["Legian"], "Kerobokan": ["Kerobokan", "Umalas"], "Pererenan": ["Pererenan"],
        "Uluwatu": ["Uluwatu", "Bukit", "Bingin", "Padang Padang", "Pecatu", "Ungasan", "Balangan"], "Jimbaran": ["Jimbaran"], "Nusa Dua": ["Nusa Dua", "Tanjung Benoa", "Benoa", "ITDC"], "Sanur": ["Sanur"], "Denpasar": ["Denpasar", "Renon"],
        "Ubud": ["Ubud", "Tegallalang", "Penestanan", "Sayan", "Payangan", "Peliatan"], "Gianyar": ["Gianyar", "Sukawati", "Celuk", "Batubulan", "Keliki", "Tampaksiring"], "Sidemen": ["Sidemen"], "Amed": ["Amed", "Tulamben"], "Candidasa": ["Candidasa"],
        "Nusa Penida": ["Nusa Penida"], "Nusa Lembongan": ["Nusa Lembongan", "Lembongan", "Nusa Ceningan", "Ceningan"], "Lovina": ["Lovina", "Singaraja", "Buleleng"], "Munduk": ["Munduk"], "Bedugul": ["Bedugul", "Bratan", "Beratan"],
        "Kintamani": ["Kintamani", "Mount Batur", "Batur"], "Tabanan": ["Tabanan"], "Tanah Lot": ["Tanah Lot"], "Jatiluwih": ["Jatiluwih"], "Seseh / Cemagi": ["Seseh", "Cemagi", "Kedungu", "Nyanyi"], "Medewi": ["Medewi"], "West Bali": ["West Bali", "Menjangan", "Pemuteran", "Perancak", "Jembrana"],
        "Karangasem": ["Karangasem", "Amlapura", "Tirta Gangga", "Tenganan", "Besakih", "Padang Bai", "Padangbai"], "Klungkung": ["Klungkung", "Semarapura"], "Bangli": ["Bangli", "Penglipuran"], "Kedonganan": ["Kedonganan"], "Serangan": ["Serangan"], "Mengwi": ["Mengwi", "Taman Ayun"],
        "Sanur / Ketewel": ["Ketewel", "Saba"], "Tejakula": ["Tejakula"], "Bali (island)": ["Bali"],
    },
    "location_elsewhere": {
        "Yogyakarta": ["Yogyakarta", "Jogja", "Yogya", "Borobudur", "Prambanan"], "Bandung": ["Bandung", "Lembang"], "Lombok": ["Lombok", "Gili", "Senggigi", "Mandalika"], "Komodo & Labuan Bajo": ["Labuan Bajo", "Komodo", "Flores"], "Raja Ampat": ["Raja Ampat", "Papua"],
        "Surabaya": ["Surabaya"], "Semarang": ["Semarang"], "Solo": ["Surakarta", "Solo"], "Malang": ["Malang", "Bromo", "Batu"], "Medan": ["Medan"], "Lake Toba": ["Lake Toba", "Samosir", "Toba"], "Makassar": ["Makassar"], "Manado": ["Manado", "Bunaken"], "Belitung": ["Belitung"], "Bintan": ["Bintan"],
        "Sumba": ["Sumba"], "Toraja": ["Toraja"], "Banyuwangi": ["Banyuwangi", "Ijen"], "Bangka": ["Bangka"], "Palembang": ["Palembang"], "Padang": ["Padang", "Bukittinggi", "West Sumatra"], "Aceh": ["Aceh", "Banda Aceh", "Weh"], "Kalimantan": ["Kalimantan", "Borneo", "Derawan", "Tanjung Puting"],
        "Sulawesi": ["Sulawesi", "Wakatobi", "Togean"], "Maluku": ["Maluku", "Moluccas", "Banda", "Ambon", "Ternate", "Seram"], "Nusa Tenggara": ["Nusa Tenggara", "NTT", "Sumbawa", "Alor", "Kupang", "Ende", "Kelimutu"], "Lampung": ["Lampung", "Krakatau", "Krakatoa", "Way Kambas"], "Cirebon": ["Cirebon"], "Pangandaran": ["Pangandaran"], "Ujung Kulon": ["Ujung Kulon"], "Anyer / Carita": ["Anyer", "Carita"], "Dieng": ["Dieng"], "Karimunjawa": ["Karimunjawa"], "Riau Islands": ["Batam", "Riau"], "Sumatra (general)": ["Sumatra"], "Java (general)": ["Java", "Central Java", "East Java", "West Java"],
    },
    "location_international": {
        "Singapore": ["Singapore"], "Kuala Lumpur": ["Kuala Lumpur", "Malaysia", "Penang", "Langkawi"], "Bangkok": ["Bangkok", "Thailand", "Phuket", "Chiang Mai", "Koh Samui"], "Hong Kong": ["Hong Kong"], "Tokyo": ["Tokyo", "Japan", "Kyoto", "Osaka", "Hokkaido"], "Seoul": ["Seoul", "South Korea", "Korea", "Jeju"],
        "Australia": ["Australia", "Sydney", "Melbourne", "Perth", "Brisbane"], "Dubai": ["Dubai", "Abu Dhabi", "UAE"], "Europe": ["Europe", "Paris", "London", "Amsterdam", "Rome", "Italy", "France", "Switzerland", "Germany", "Spain", "Portugal", "Vienna", "Prague", "Vilnius"], "Maldives": ["Maldives"], "Sri Lanka": ["Sri Lanka", "Colombo"],
        "India": ["India", "Mumbai", "Delhi", "Kerala", "Rajasthan"], "Nepal / Bhutan": ["Nepal", "Bhutan", "Kathmandu"], "Vietnam": ["Vietnam", "Hanoi", "Ho Chi Minh", "Da Nang", "Hoi An"], "Philippines": ["Philippines", "Manila", "Cebu", "Palawan"], "Cambodia / Laos": ["Cambodia", "Siem Reap", "Laos", "Luang Prabang"], "Taiwan": ["Taiwan", "Taipei"], "China": ["China", "Shanghai", "Beijing", "Macau"],
        "USA": ["New York", "Los Angeles", "San Francisco", "Las Vegas", "Hawaii", "United States"], "New Zealand": ["New Zealand", "Auckland", "Queenstown"], "Turkey": ["Turkey", "Istanbul", "Cappadocia"], "Africa": ["Africa", "Kenya", "Tanzania", "Cape Town", "Morocco", "Marrakech", "Egypt"], "Middle East": ["Qatar", "Doha", "Oman", "Jordan"],
    },
    "amenities": {
        "Infinity pool": ["infinity pool"], "Private pool": ["private pool", "plunge pool"], "Rooftop": ["rooftop"], "Beachfront": ["beachfront", "beach access", "on the beach"], "Ocean view": ["ocean view", "sea view", "clifftop", "cliff-top", "cliffside"], "Sunset view": ["sunset view", "sunset spot", "sunset"],
        "Rice-field view": ["rice field", "rice paddies", "paddy view", "rice terraces"], "Jungle view": ["jungle view", "jungle", "rainforest"], "River view": ["riverside", "river view", "Ayung"], "Lagoon": ["lagoon pool", "lagoon"], "Swim-up bar": ["swim-up bar", "pool bar"], "Cabana / day bed": ["cabana", "day bed", "daybed", "sunbed", "sun lounger"],
        "Kids club": ["kids club", "kids' club", "kid's club", "children's club", "playground", "kids menu", "child-friendly", "family-friendly"], "Butler": ["butler"], "Private dining": ["private dining", "private room", "function room", "chef's table"], "Wine cellar": ["wine cellar"], "Live music": ["live music", "live band", "DJ", "resident DJ"], "Karaoke": ["karaoke"],
        "Shisha": ["shisha", "hookah"], "Cigar lounge": ["cigar"], "Outdoor seating": ["al fresco", "alfresco", "terrace", "outdoor seating", "garden seating"], "Garden": ["garden", "courtyard"], "Co-working": ["co-working", "coworking", "laptop-friendly", "meeting rooms", "ballroom", "MICE"], "Parking": ["parking", "valet"], "Wi-Fi": ["wifi", "wi-fi"],
        "Pet-friendly": ["pet-friendly", "dog-friendly", "pets welcome"], "Halal": ["halal", "no pork no lard", "pork-free"], "Vegetarian options": ["vegetarian"], "Vegan options": ["vegan", "plant-based"], "Gluten-free": ["gluten-free"], "Wheelchair accessible": ["wheelchair", "accessible", "step-free"], "Spa": ["in-house spa", "spa"], "Gym": ["gym", "fitness centre", "fitness center"],
        "Yoga shala": ["yoga shala", "yoga studio", "shala"], "Sauna / steam": ["sauna", "steam room", "hammam", "jacuzzi", "hot tub", "onsen"], "Cold plunge / ice bath": ["ice bath", "cold plunge"], "Buffet": ["buffet"], "Free flow": ["free flow", "free-flow", "bottomless"], "Breakfast included": ["breakfast included", "daily breakfast"], "Airport transfer": ["airport transfer", "shuttle"], "Smoking area": ["smoking area", "smoking room"],
        "Late night": ["late night", "open late", "24 hours", "24-hour"], "Delivery": ["delivery", "takeaway", "take-away", "GoFood", "GrabFood"], "Sports screening": ["big screen", "sports bar", "live sports"], "Surf break": ["surf break", "surf spot", "reef break"], "Dive centre": ["dive centre", "dive center", "dive shop", "PADI"],
    },
    "vibe": {
        "Romantic": ["romantic"], "Luxury": ["luxury", "luxurious", "opulent", "five-star", "5-star"], "Hidden gem": ["hidden gem", "under the radar", "secret", "tucked away"], "Trendy": ["trendy", "hip", "hipster", "buzzing", "happening", "see-and-be-seen"], "Casual": ["casual", "relaxed", "no-frills", "laidback", "laid-back"], "Cozy": ["cozy", "cosy", "intimate", "homely"],
        "Lively": ["lively", "vibrant", "energetic", "bustling"], "Bohemian": ["bohemian", "boho", "beachy"], "Artsy": ["artsy", "creative", "design-led", "arty"], "Scenic": ["scenic", "breathtaking view", "panoramic", "stunning views", "sweeping views"], "Party": ["party", "nightlife", "clubbing", "late night"], "Serene": ["serene", "tranquil", "zen", "peaceful", "calm", "sanctuary", "oasis"],
        "Classic": ["classic", "timeless", "old-world", "institution", "legendary", "iconic"], "Instagrammable": ["instagrammable", "instaworthy", "insta-worthy", "photogenic", "aesthetic"], "Chic": ["chic", "stylish", "elegant", "sophisticated", "refined"], "Rustic": ["rustic", "earthy", "raw"], "Authentic": ["authentic", "traditional", "local"], "Modern": ["modern", "contemporary", "minimalist", "industrial", "sleek"],
        "Tropical": ["tropical", "island", "resort-style"], "Glamorous": ["glamorous", "glam", "lavish", "decadent", "indulgent"], "Quirky": ["quirky", "whimsical", "eclectic", "playful"], "Family-friendly": ["family-friendly", "kid-friendly", "child-friendly"], "Nostalgic": ["nostalgic", "retro", "vintage", "heritage charm", "colonial charm"], "Wholesome": ["wholesome", "healthy", "mindful", "conscious"], "Exclusive": ["exclusive", "private", "members-only", "VIP"], "Cool": ["cool", "edgy", "underground"],
    },
    "occasion": {
        "Date night": ["date night", "anniversary", "Valentine's", "Valentine", "romantic dinner"], "Business": ["business lunch", "business dinner", "client", "corporate", "meeting", "MICE", "team building", "team-building"], "Celebration": ["celebration", "birthday", "wedding", "party", "gathering", "reunion"], "Family day": ["with kids", "school holiday", "family day", "family outing", "family getaway"],
        "Brunch": ["brunch", "Sunday brunch", "breakfast"], "Night out": ["night out", "after-work", "after work", "girls' night", "boys' night"], "Weekend getaway": ["weekend getaway", "staycation", "short break", "long weekend", "escape", "getaway"], "Group": ["big group", "large group", "group of friends", "group booking"], "Solo": ["solo", "me time", "solo traveller"],
        "Sunset": ["sunset", "golden hour", "sundowner"], "Afternoon tea": ["afternoon tea", "high tea"], "Wedding": ["wedding", "weddings", "honeymoon", "proposal", "bridal", "bachelor", "bachelorette", "hen party"], "Festive": ["Christmas", "New Year", "New Year's Eve", "festive season", "Thanksgiving"], "Ramadan": ["Ramadan", "iftar", "buka puasa", "Lebaran", "Eid"], "Lunar New Year": ["Chinese New Year", "Lunar New Year", "Imlek"], "Nyepi / Galungan": ["Nyepi", "Galungan", "Kuningan", "Saraswati"], "Mother's / Father's Day": ["Mother's Day", "Father's Day"], "Halloween": ["Halloween"], "Independence Day": ["Independence Day", "17 August"],
        "Digital nomad": ["digital nomad", "remote work", "workation"], "Retreat": ["retreat", "yoga retreat", "wellness retreat", "detox"], "Surf trip": ["surf trip", "surfing holiday"], "Diving trip": ["dive trip", "liveaboard"], "Road trip": ["road trip", "itinerary", "day trip", "island hopping"],
    },
    "audience": {
        "Expat": ["expat", "expats", "expatriate", "expatriates", "international community"], "Tourist": ["tourist", "tourists", "visitor", "visitors", "traveller", "travellers", "traveler", "travelers"], "Local": ["locals", "Jakartans", "Balinese", "residents"], "Family": ["family", "families", "kids", "children", "parents", "toddlers", "teens"],
        "Business traveller": ["business traveller", "business travellers", "business traveler", "corporate travellers"], "Couples": ["couples", "honeymooners", "lovebirds"], "Digital nomad": ["digital nomads", "digital nomad", "remote workers"], "Solo traveller": ["solo traveller", "solo travelers", "solo traveller"], "Backpacker": ["backpacker", "backpackers", "budget travellers"], "Retiree": ["retirees", "retirement", "retire"], "Students": ["students", "teenagers"], "Surfers": ["surfers"], "Divers": ["divers"], "Yogis": ["yogis", "yogi"], "Foodies": ["foodies", "foodie"], "Muslim travellers": ["Muslim travellers", "Muslim-friendly", "halal tourism"], "LGBTQ": ["LGBT", "LGBTQ", "gay-friendly"], "Seniors": ["seniors", "elderly"], "Women": ["women", "female travellers", "ladies"],
    },
    "topic": {
        "Sustainability": ["sustainability", "sustainable", "eco", "eco-friendly", "green living", "zero waste", "zero-waste", "plastic", "recycling", "climate", "environment", "conservation"], "Heritage": ["heritage", "history", "colonial", "conservation"], "Health": ["health", "wellbeing", "well-being", "mental health", "nutrition", "fitness", "medical"], "Education": ["education", "school", "schools", "university", "curriculum", "students"],
        "Business": ["business", "economy", "industry", "entrepreneur", "startup", "start-up", "investment"], "Finance": ["finance", "banking", "tax", "insurance", "investment"], "Property": ["property", "real estate", "apartment", "apartments", "housing", "residences", "developer"], "Art": ["art", "artist", "painting", "sculpture", "street art", "exhibition"], "Design": ["design", "interior design", "architecture", "architect"],
        "Music": ["music", "musician", "jazz", "concert", "album", "band", "DJ"], "Film": ["film", "cinema", "movie", "documentary"], "Fashion": ["fashion", "designer", "runway", "style", "collection"], "Photography": ["photography", "photographer", "photo essay"], "Literature": ["literature", "book", "books", "author", "poetry", "writers festival", "novel"], "Culture": ["culture", "tradition", "ceremony", "ritual", "religion", "customs", "language", "dance"],
        "Sports": ["sports", "football", "golf", "running", "marathon", "padel", "tennis", "rugby", "badminton", "basketball", "surfing", "MotoGP", "Formula"], "Community": ["community", "charity", "NGO", "foundation", "volunteer", "social impact", "fundraising"], "Diplomacy": ["diplomacy", "embassy", "ambassador", "bilateral", "consulate"], "Technology": ["technology", "digital", "startup", "app", "AI", "artificial intelligence", "fintech", "e-commerce"],
        "Travel": ["travel", "destination", "getaway", "explore", "itinerary", "tourism"], "Transport": ["transport", "traffic", "MRT", "LRT", "airport", "commuting", "toll road", "TransJakarta", "flight", "airline"], "Expat life": ["living in Jakarta", "living in Bali", "visa", "KITAS", "relocation", "moving to"], "Made in Indonesia": ["made in Indonesia", "local brand", "local brands", "homegrown", "Indonesian craft", "artisan"],
        "Family & parenting": ["parenting", "kids", "family activities", "children"], "Religion & spirituality": ["Hindu", "Hinduism", "Islam", "Muslim", "Christian", "church", "mosque", "temple", "spiritual", "spirituality", "meditation"], "Food & drink": ["culinary", "gastronomy", "recipe", "recipes", "cooking", "chef", "wine", "coffee", "cocktail"], "Nightlife": ["nightlife", "clubbing", "party", "DJ", "club"], "Weddings": ["wedding", "weddings", "bridal", "honeymoon"],
        "Pets & animals": ["dogs", "dog", "cats", "animal welfare", "wildlife", "sea turtles", "turtle", "elephant", "monkeys"], "Agriculture & food systems": ["farmers", "farming", "agriculture", "coffee farmers", "rice farmers", "seaweed", "fishermen", "fishing"], "Urban issues": ["flooding", "flood", "pollution", "air quality", "urban", "city planning", "governor", "Anies", "Ridwan Kamil", "Pramono"], "Covid-19": ["Covid", "Covid-19", "pandemic", "lockdown", "PSBB", "PPKM", "new normal", "quarantine", "vaccine"],
        "History of tourism": ["tourism history", "mass tourism", "overtourism"], "Craft spirits": ["arak", "gin", "rum", "distillery", "brewery", "craft beer", "winery", "vineyard"], "Coffee culture": ["coffee", "barista", "roastery", "specialty coffee"], "Spa & beauty": ["spa", "massage", "facial", "salon", "beauty", "skincare"], "Weddings & romance": ["romance", "romantic", "love"],
    },
    "venue_kind": {
        "Beach club": ["beach club", "beach clubs"], "Warung": ["warung", "warungs"], "Food hall / court": ["food hall", "food court", "food market"], "Cooking class": ["cooking class", "cooking classes", "culinary class"], "Co-working": ["co-working", "coworking"], "Villa": ["villa", "villas"], "Glamping": ["glamping", "camping", "campsite"], "Hostel": ["hostel", "hostels"], "Coffee shop": ["coffee shop", "cafe", "café", "roastery"], "Speakeasy": ["speakeasy"],
        "Brewery / taproom": ["brewery", "microbrewery", "taproom", "brewpub"], "Distillery": ["distillery"], "Winery": ["winery", "vineyard"], "Gallery": ["gallery", "art space"], "Museum": ["museum"], "Waterpark": ["waterpark", "water park"], "Zoo / safari": ["zoo", "safari", "bird park", "butterfly park", "elephant park", "aquarium"], "Surf school": ["surf school", "surf camp", "surf lessons"], "Dive centre": ["dive centre", "dive center", "dive resort"], "Yoga studio": ["yoga studio", "yoga shala", "yoga barn", "yoga retreat"],
        "Gym / fitness studio": ["gym", "fitness studio", "fitness centre", "crossfit", "boxing gym", "pilates studio"], "Barbershop": ["barbershop", "barber"], "Nail bar": ["nail bar", "nail salon", "manicure"], "Tattoo studio": ["tattoo"], "Cinema": ["cinema", "movie theatre", "movie theater", "XXI", "CGV"], "Bookshop": ["bookshop", "bookstore", "library"], "Concept store": ["concept store"], "Florist": ["florist"], "Bakery": ["bakery", "boulangerie", "patisserie"], "Gelato / dessert": ["gelato", "gelateria", "ice cream", "dessert bar", "dessert shop"], "Tea house": ["tea house", "teahouse", "tea room"],
        "Supper club": ["supper club"], "Chef's table": ["chef's table"], "Wine bar": ["wine bar"], "Sake bar": ["sake bar"], "Cocktail bar": ["cocktail bar", "mixology bar"], "Rooftop bar": ["rooftop bar", "sky bar", "skybar"], "Sports bar": ["sports bar"], "Karaoke": ["karaoke", "KTV"], "Nightclub": ["nightclub", "night club", "club"], "Lounge": ["lounge"], "Cigar lounge": ["cigar lounge"], "Billiards / bowling": ["billiard", "bowling", "pool hall", "arcade", "trampoline", "escape room"],
        "Golf course": ["golf course", "golf club", "driving range"], "Padel / tennis": ["padel", "tennis court", "tennis club"], "Climbing gym": ["climbing gym", "bouldering", "rock climbing"], "Cycling": ["cycling", "bike tour", "bicycle"], "Running club": ["running club", "run club"], "Rafting": ["rafting", "white water"], "Trekking / hiking": ["trekking", "hiking", "trek", "sunrise trek"], "Snorkelling / diving": ["snorkelling", "snorkeling", "diving", "scuba", "freediving"], "Surfing": ["surfing", "surf"], "Kitesurfing / sailing": ["kitesurf", "kitesurfing", "sailing", "catamaran", "yacht"], "Cruise": ["cruise", "sunset cruise", "dinner cruise", "liveaboard", "phinisi"],
        "Helicopter / balloon": ["helicopter", "hot air balloon"], "ATV / buggy": ["ATV", "quad bike", "buggy", "jungle buggies"], "Horse riding": ["horse riding", "horseback"], "Waterfall": ["waterfall", "waterfalls"], "Hot spring": ["hot spring", "hot springs"], "Rice terrace": ["rice terrace", "rice terraces"], "Volcano": ["volcano", "Mount Batur", "Mount Agung", "Bromo"], "Temple": ["temple", "temples", "pura"], "Palace": ["palace", "water palace"], "Market": ["market", "pasar", "night market", "farmers market", "flea market"], "Mall": ["mall", "shopping mall", "shopping centre", "plaza"],
        "Serviced apartment": ["serviced apartment", "serviced apartments", "aparthotel", "residence"], "Boutique hotel": ["boutique hotel"], "Eco lodge": ["eco lodge", "eco-lodge", "eco resort", "eco-resort", "treehouse", "tree house"], "Retreat centre": ["retreat centre", "retreat center", "healing centre", "wellness centre", "wellness center"], "Clinic / hospital": ["clinic", "hospital", "aesthetic clinic", "dental clinic"], "School": ["international school", "school", "university", "kindergarten", "preschool"], "Embassy": ["embassy", "consulate"], "Church / mosque": ["church", "cathedral", "mosque"],
        "Convention centre": ["convention centre", "convention center", "exhibition hall", "JCC", "ICE BSD", "JIExpo"], "Theatre / concert hall": ["theatre", "theater", "concert hall", "Ciputra Artpreneur", "Taman Ismail Marzuki", "Salihara", "Aula Simfonia"], "Stadium": ["stadium", "GBK", "arena"], "Pop-up": ["pop-up", "pop up"], "Bazaar": ["bazaar", "bazar"], "Farm": ["farm", "organic farm", "plantation", "coffee plantation"],
    },
}
