"""Hand-authored proposals and the decision registry.

This is the one place where judgement is written down instead of computed:

* `BALI_PROPOSALS`     the proposed facet decomposition of every Bali
                       category (Bali has no E1.4 draft); each carries its
                       reasoning and the decision ids it depends on.
* `JAKARTA_ADJUSTMENTS` amendments to E1.4's Jakarta draft where this pack's
                       evidence changes the call. Everything not listed is
                       carried from E1.4 unchanged.
* `DECISIONS`          the cross-city decision registry -- the ~25 things a
                       human has to confirm. E1.4's 18 decisions are folded
                       in (carried_from), several merged, Bali's added.

The evidence attached to each decision is computed at run time from the
corpus (decide.py); the text here is the question and the recommendation.
"""
from __future__ import annotations

# ---------------------------------------------------------------------------
# Decision registry. `affects` is filled from category memberships at runtime.
# kind: policy | vocabulary | mapping | split | scope
# ---------------------------------------------------------------------------
DECISIONS: list[dict] = [
    {"id": "D01", "kind": "policy", "title": "Guide vs listing boundary (cross-cutting)", "carried_from": "E1.4 #11/#12/#13/#16",
     "question": "Adopt: a roundup tied to a period (year in title, '[Updated]', seasonal) is `listing` (540-day half-life, series_key dedup); a timeless how-to/area piece is `guide` (evergreen). §4 maps the Guide categories wholesale to `guide`.",
     "recommendation": "Adopt the boundary. It is what lets the 2019 editions sink while the current '[Updated]' edition stays fresh through dedup.",
     "options": ["adopt (recommended)", "everything in a *Guide category is `guide` (§4 literal)", "everything period-stamped is `guide` but decays like listing"]},
    {"id": "D02", "kind": "policy", "title": "Legacy offers and events have no end date", "carried_from": "E1.4 #1/#17",
     "question": "`offer` hard-expires at campaign.ends_at and `event` at event.ends_at (§8.A), but legacy posts have neither. Proposed: E1.8/E2.1 extracts a date from the text where present; otherwise offers expire at publish + 90 days and events at publish + 30 days. Expired items stay searchable, never in rails.",
     "recommendation": "Accept the fallback windows. Almost every offer before 2024 is dead anyway; the only live question is the window for recent ones.",
     "options": ["accept 90/30 (recommended)", "different windows", "no fallback -- undated legacy offers/events are treated as expired on load"]},
    {"id": "D03", "kind": "vocabulary", "title": "Approve the proposed `opinion` format", "carried_from": "E1.4 #4",
     "question": "298 Opinion articles across both cities (plus Bali's Winocracy/Stranger In Paradise columns) have no honest §4 format. Proposed `opinion` with a 540-day half-life. Fallback: `feature` (evergreen), which keeps 2016 columns permanently fresh.",
     "recommendation": "Approve.", "options": ["approve (recommended)", "reject -> feature"]},
    {"id": "D04", "kind": "vocabulary", "title": "Approve `editorial/culture` (subtype)", "carried_from": "E1.4 #2/#8",
     "question": "Arts and culture coverage that is neither a dated event nor a venue: Jakarta Art/Culture/Design/Music/Film features, and most of Bali's Culture family (Cultural Observer, Dance and Music, Ceremonies & Festivals, Everyday Bali, Myths and Legends, Art In Bali). Without the subtype they force-fit into `news` or `people`.",
     "recommendation": "Approve. Bali alone has ~600 articles that land here.", "options": ["approve (recommended)", "reject -> editorial/news or editorial/people"]},
    {"id": "D05", "kind": "vocabulary", "title": "Approve `editorial/lifestyle` (subtype)", "carried_from": "E1.4 #5/#14",
     "question": "Service journalism with no venue subject (Jakarta Health/Lifestyle/Green Living; Bali Lifestyle-only pieces and the lockdown 'Home Life' columns). Same force-fit problem as D04.",
     "recommendation": "Approve.", "options": ["approve (recommended)", "reject -> editorial/news"]},
    {"id": "D06", "kind": "vocabulary", "title": "Approve the `international` location root", "carried_from": "E1.4 #6",
     "question": "`location` is required; World Traveller (94) and part of Travel are about Singapore, Dubai, Hong Kong, Switzerland... Seeded as a single leaf; children added once E2.1 reports the destination distribution.",
     "recommendation": "Approve.", "options": ["approve (recommended)", "reject -> these articles get `indonesia` (wrong) or are excluded from location filters"]},
    {"id": "D07", "kind": "policy", "title": "Print-issue categories carry no facets", "carried_from": "E1.4 #15",
     "question": "34 Jakarta categories are themes of individual 2019-2020 print issues (~205 posts, 2-10 each). Proposed: no facet mapping; `series_key = issue:<slug>`; format prior `feature`; classifier assigns everything else from content.",
     "recommendation": "Confirm. One decision retires 34 categories.", "options": ["confirm (recommended)", "map each theme to a topic anyway"]},
    {"id": "D08", "kind": "scope", "title": "Bali's column and 'Home Life' archive categories: series_key, and are the lockdown columns migrated at all?",
     "question": "Bali carries column/series categories that are not subjects: Chaine Des Rottiseurs (24, 2015-18 dinner reports), Stranger In Paradise (21), Winocracy (9), NOW! Bali Podcast (27), Video (11), Behind the Bar (7), and the 2020 lockdown 'Home Life' series -- Cook and Mix (16), Must Watch Movies (13), Music to the Ears (11), Health & Wellness (7), Home Life (1). Proposed: `series_key = column:<slug>` for all; facets from content (mostly editorial/lifestyle|culture + feature). The movie/playlist columns have no Jakarta/Bali subject at all.",
     "recommendation": "Keep them all (they are cheap and searchable) but exclude the no-local-subject columns (Must Watch Movies, Music to the Ears) from the rails via the quality floor; carry series_key for every column.",
     "options": ["keep all, series_key, rails-excluded for the two non-local columns (recommended)", "keep all, no exclusions", "drop Must Watch Movies + Music to the Ears + Home Life from the migration"]},
    {"id": "D09", "kind": "policy", "title": "Uncategorized (both cities) -> review queue; non-articles excluded", "carried_from": "E1.4 #7",
     "question": "Jakarta 83 + Bali 71 posts carry only Uncategorized, including non-editorial pages ('Order Form - NOW! Magazines', 'Purchasing NOW! Bali & TIMELESS Bali Magazines', 'USA NATIONAL DAY'). Proposed: no prior; every one goes to the E2.8 review queue regardless of classifier confidence; E1.8 flags obvious non-articles for exclusion below the quality floor.",
     "recommendation": "Confirm.", "options": ["confirm (recommended)", "trust the classifier at the normal threshold"]},
    {"id": "D10", "kind": "policy", "title": "Multi-category resolution order: Yoast primary > most specific child > parent container",
     "question": "Both sites file under parent containers alongside children (Bali: Dining Offers+Restaurants and Bars 188, Lifestyle+Shopping 109, Lifestyle+Spa 90, Explore Bali+Opinion 41; Jakarta: Dining Offers+Stay Offers 33). Bali has a Yoast primary on 90% of posts, Jakarta on 51%. Proposed: the prior comes from the Yoast primary when present; otherwise from the most specific (deepest) category; a parent-only category (Lifestyle, Culture, Explore Bali, Offers, Dining, Features...) is a weak prior for the articles that carry nothing else.",
     "recommendation": "Adopt. It makes the eleven container categories mostly moot.", "options": ["adopt (recommended)", "always combine all categories", "ignore Yoast primary"]},
    {"id": "D11", "kind": "vocabulary", "title": "Approve `do/sports-activity` (subtype)", "carried_from": "E1.4 #9",
     "question": "Participatory sport venues and clubs (padel centres, climbing gyms, running clubs) versus `event/sports` (a dated fixture) versus features about sport. Jakarta Sports & Activities (61) mixes all three; Bali has the same mix inside Community/Activities.",
     "recommendation": "Approve and let the classifier pick among the three.", "options": ["approve (recommended)", "reject -> do/adventure or wellness/gym"]},
    {"id": "D12", "kind": "vocabulary", "title": "Approve the proposed event subtypes: `performance`, `screening`, `pop-up`", "carried_from": "E1.4 #10",
     "question": "`concert` is music-only and `exhibition` is visual arts; theatre/dance (a large slice of Jakarta Art and Events), film festivals (Jakarta Film 35) and pop-up markets have no §4 node.",
     "recommendation": "Approve all three.", "options": ["approve all (recommended)", "approve performance + screening only", "reject -> festival/concert"]},
    {"id": "D13", "kind": "vocabulary", "title": "Approve the proposed wellness subtypes: `salon`, `retreat`",
     "question": "Bali Spa and Wellness (209) and Lifestyle carry beauty venues (Toni&Guy, facials, nail bars) and multi-day retreats (COMO Shambhala, Fivelements, detox programmes) that have no §4 node; `spa` would absorb both and blur Row 1 matching.",
     "recommendation": "Approve both.", "options": ["approve both (recommended)", "approve retreat only", "reject -> spa"]},
    {"id": "D14", "kind": "vocabulary", "title": "Location tree: approve E1.4's proposed nodes and the corpus-found gaps",
     "question": "E1.4 proposed 40+ location nodes beyond §4 (Kuningan, Kota Tua, Cikini, East Jakarta, Denpasar, Legian, Nusa Penida, Surabaya...). The corpus scan below shows how often each is actually named, and surfaces places the tree lacks entirely (Bali: Tabanan/Tanah Lot, Kintamani/Batur, Bedugul/Munduk, Nusa Lembongan, West Bali/Menjangan, Karangasem towns; Jakarta: Kebayoran Baru, Cilandak/TB Simatupang, Kemayoran, Pluit, Jatinegara/Condet).",
     "recommendation": "Approve every proposed node with >= 10 corpus mentions; add the corpus-found gaps with >= 20 mentions; drop proposed nodes with < 5 mentions.", "options": ["approve by the mention thresholds (recommended)", "approve E1.4's list as-is", "§4 tree only"]},
    {"id": "D15", "kind": "vocabulary", "title": "Cuisine list: additions and removals from corpus evidence",
     "question": "The 27 seeded cuisines were invented, not extracted. The scan shows which never appear (removal candidates) and which frequent cuisines are missing (e.g. Singaporean/Malaysian, dessert/bakery/coffee as reader-facing 'cuisines', vegan/plant-based as a cuisine rather than only an amenity).",
     "recommendation": "Remove seed cuisines with zero title mentions and < 10 body mentions; add candidates with >= 40 mentions; keep dietary needs in amenities as designed.", "options": ["apply thresholds (recommended)", "keep the seed as-is", "hand-pick"]},
    {"id": "D16", "kind": "vocabulary", "title": "Vibe, occasion, amenity, audience, topic: prune the unused, add the frequent",
     "question": "Same check for the other invented lists. Some seed terms have zero corpus support; some corpus-frequent notions have no term (wedding/honeymoon as an occasion, digital-nomad as an audience, Ramadan/festive as occasions, jungle/rice-field view and private pool as amenities, Covid-19/urban issues as topics).",
     "recommendation": "Prune zero-support terms unless a filter UI needs them; add candidates above the report's threshold.", "options": ["apply (recommended)", "keep seed as-is"]},
    {"id": "D17", "kind": "mapping", "title": "Experience Offers (both cities): hotel-experience packages, not a `do` category", "carried_from": "E1.4 #3",
     "question": "Is 'Experience Offers' a stay category (hotel packages) or a do category (activities)? Evidence in both cities: it is hotel 'experience' marketing -- F&B, wellness, festive programmes, kids' activities -- at a hotel; the venue is the hotel but the subject is often its restaurant or spa. Proposed: format `offer` fixed; type per article with `stay/hotel` as the prior; classifier may pick eat/wellness/do/event.",
     "recommendation": "Accept 'type per article, stay prior, format offer'. Do not map to `do`.", "options": ["accept (recommended)", "stay/hotel for all", "do/* for all"]},
    {"id": "D18", "kind": "mapping", "title": "Bali 'Explore Bali' is not a `do` category -- it is a container plus an opinion column",
     "question": "LIVE_RECON N3 read `explore-bali` (117) as `do`. The articles disagree: 41 co-occur with Opinion ('Parking and Deliveries, The Headache Continues', 'Democracy in Action in Indonesia'), the rest are the parent of Activities/Cultural Sites/Destinations/Bali with Kids/Nature/Parks. Proposed: no type prior from 'Explore Bali' itself; children carry the priors; Explore Bali+Opinion -> editorial/opinion.",
     "recommendation": "Accept -- treat as container (D10) and let Opinion win when both are present.", "options": ["accept (recommended)", "do/* prior for all 117"]},
    {"id": "D19", "kind": "mapping", "title": "Community (both cities): `news` or `feature` as the format prior?",
     "question": "E1.4 gave Jakarta Community `editorial/news + news` (MEDIUM). Bali Community (152) reads as features and profiles of NGOs and initiatives ('Solemen Bali', 'Mission Paws'ible', 'Quantum Temple') -- evergreen, not 21-day news. A wrong prior here decays 300 articles to nothing or keeps dated charity events fresh.",
     "recommendation": "Prior `feature` for both cities; classifier switches to `event` (dated fundraisers) or `news` (announcements) when the text says so; topic `community` always.", "options": ["feature prior for both (recommended)", "keep E1.4's news prior", "per article, no prior"]},
    {"id": "D20", "kind": "mapping", "title": "Bali 'Dining Offers' (487): a third read as dining news, not offers",
     "question": "Jakarta Dining Offers are unambiguous promotions (cue: offer 70%). Bali's are weaker (offer 45%, news 16%, no signal 34%): many 2016-2019 pieces are new-menu or new-restaurant write-ups filed as offers, and 188 co-occur with Restaurants and Bars. Mapping all 487 to `offer` hard-expires them; mapping to `news` decays them in 21 days -- either way they leave the rails, but `offer` also excludes them from 'similar' rows once expired.",
     "recommendation": "Format per article with `offer` as the prior (Yoast primary decides when it is Restaurants and Bars); accept that the classifier will relabel roughly a third as news.", "options": ["offer prior, per-article override (recommended)", "offer for all 487", "news for the pre-2020 ones"]},
    {"id": "D21", "kind": "mapping", "title": "Bali 'News' (1,067 -- 24% of the archive): format `news` as prior, type per article",
     "question": "The largest category in either city. Cue instrument: news 24%, event 21%, offer 11%, unclear 31%; type is spread across stay/event/eat/editorial. Proposed: format `news` prior (21-day decay), type per article, location bali. A quarter will be relabelled event/offer by the classifier.",
     "recommendation": "Accept -- same treatment E1.4 gave Jakarta News. Flagged only because of its size: it is the single largest lever on Bali's freshness curve.", "options": ["accept (recommended)", "per-article format, no prior"]},
    {"id": "D22", "kind": "mapping", "title": "Weddings (Bali, 17) and romance content: `occasion` term or a type?",
     "question": "No §4 node fits weddings: venues are villas/resorts (stay), services are shops, the pieces are listings/guides. The seed has `occasion/celebration` with 'wedding' as an alias. Proposed: type per article, format listing|guide, occasion `celebration` -- or add a dedicated `occasion/wedding` (corpus: see vocabulary counts) so the itinerary/filters can target it.",
     "recommendation": "Add `occasion/wedding` (aliases honeymoon, proposal, bridal); it is a real reader intent in Bali.", "options": ["add occasion/wedding (recommended)", "use celebration"]},
    {"id": "D23", "kind": "split", "title": "Bali 'Lifestyle' (243) is a container of Spa, Shopping and beauty -- not one thing",
     "question": "242 of 243 also carry a child category (Shopping 114, Spa and Wellness 91, Bar Guide 26, Bali with Kids 7...); exactly one post carries Lifestyle alone. The Lifestyle-flavoured content is beauty (salons, facials, fragrance), fashion and misc. features. No single type/format prior is honest. Proposed: container (D10) -- the child's prior wins; for the residue, type per article (wellness/salon likely, needs D13), format per article, editorial/lifestyle fallback (D05).",
     "recommendation": "Accept; nothing to map at the parent level.", "options": ["accept (recommended)", "wellness prior for all"]},
    {"id": "D24", "kind": "mapping", "title": "Bali 'Culture' family: `culture`+`feature` vs `heritage`+`heritage` split",
     "question": "Cultural Observer (110), Dance and Music (75), Ceremonies & Festivals (45), Myths and Legends (30), Everyday Bali (30), Bali History (22), Stranger In Paradise (21) are all evergreen explainers. Both candidate formats are evergreen so decay is unaffected; the choice decides which reader filter (Culture vs History) they surface under. Proposed: Bali History, Myths and Legends, Stranger In Paradise -> editorial/heritage + heritage; the rest -> editorial/culture + feature (needs D04).",
     "recommendation": "Accept the split as proposed.", "options": ["accept (recommended)", "all heritage", "all culture"]},
    {"id": "D25", "kind": "mapping", "title": "Bali 'Art In Bali' (136) and Jakarta 'Art' (244): type/format per article, topic art",
     "question": "Both mix dated exhibitions (event/exhibition + event), artist profiles (editorial/people + people), commentary and buying guides. Only `topic: art` is certain. Proposed: no type/format prior; classifier decides with the listed alternates; the embedding clusters below show the split.",
     "recommendation": "Accept -- do not force a type.", "options": ["accept (recommended)", "event/exhibition prior"]},
    {"id": "D26", "kind": "mapping", "title": "Jakarta 'Business' (186): a fifth are hotel corporate announcements",
     "question": "E1.4: editorial/business + feature (MEDIUM). The cue instrument reads 19% as `stay` (hotel openings, GM appointments, joint ventures filed under Business) and format splits news/feature/opinion. Proposed: keep editorial/business as the prior but let type switch to stay/eat when a venue is the subject; format per article.",
     "recommendation": "Accept type-switchable prior; format per article.", "options": ["accept (recommended)", "keep E1.4 as-is"]},
    {"id": "D27", "kind": "scope", "title": "Bali categories with 0-3 published posts and the WP-only categories",
     "question": "Features (3), Home Life (1), Offers (1), Mapping Bali (0 published; 41 in WP's count are non-post types), Archives (0). Proposed: no mapping needed -- Features/Home Life/Offers articles are classified from content; Mapping Bali and Archives are dropped as empty containers.",
     "recommendation": "Confirm.", "options": ["confirm (recommended)"]},
]

# ---------------------------------------------------------------------------
# Bali proposals. Fields: type, subtype, format, location, per_article,
# facets, series_key, kind, confidence, decisions, reasoning, alternates,
# container (True when the category is a parent whose children carry the prior)
# ---------------------------------------------------------------------------
_B = "bali"


def _p(type_=None, subtype=None, format_=None, location=_B, per_article=(), facets=None, series_key=None, kind="editorial",
       confidence="high", decisions=(), reasoning="", alternates=(), container=False, auto=True):
    return {"type": type_, "subtype": subtype, "format": format_, "location": location, "per_article": list(per_article),
            "facets": facets or {}, "series_key": series_key, "kind": kind, "confidence": confidence, "decisions": list(decisions),
            "reasoning": reasoning, "alternates": list(alternates), "container": container, "auto": auto}


BALI_PROPOSALS: dict[str, dict] = {
    "News": _p(None, None, "news", _B, ("type", "subtype"), confidence="high", decisions=("D21",), auto=False,
               reasoning="Catch-all. Format news is the honest prior for a category literally named News; type is spread across hotels, events, restaurants and civic pieces. Same treatment E1.4 gave Jakarta News.",
               alternates=("stay/hotel + news (openings, appointments)", "event/* + event when a dated happening is announced", "format offer for festive promotions filed as news")),
    "Dining Offers": _p("eat", "restaurant", "offer", _B, ("format",), confidence="medium", decisions=("D02", "D20"), auto=False,
                        reasoning="Type eat is certain (cue 72%). Format is weaker than Jakarta's: a third read as new-menu/new-venue news.",
                        alternates=("format news for menu launches and openings", "drink/bar when the outlet is a bar (cue 10%)")),
    "Restaurants and Bars": _p("eat", "restaurant", None, _B, ("format",), confidence="high", decisions=(),
                               reasoning="Parent of Dining News/Reviews/Bar Guide/Restaurant Guide, but 360 posts carry it directly (2014-2020). Type eat with drink as the alternate (cue eat 74%, drink 13%); format per article (news/review/listing).",
                               alternates=("drink/bar|beach-club for bar pieces", "format review (first-person visits)", "format listing ('7 Fabulous Foodie Pleasers in Ubud')"), container=True),
    "Dining News": _p("eat", "restaurant", "news", _B, (), confidence="high",
                      reasoning="Matches the §4 worked example and Jakarta's mapping.", alternates=("drink/* for bar news", "format offer for promotions filed as news")),
    "Lifestyle": _p(None, None, None, _B, ("type", "subtype", "format"), confidence="low", decisions=("D23", "D05", "D13"), auto=False, container=True,
                    reasoning="Container: 242 of 243 also carry a child (Shopping 114, Spa and Wellness 91, Bar Guide 26, Bali with Kids 7); only one post carries Lifestyle alone. Beauty (salons, facials), fashion and misc. features dominate the parent's own flavour.",
                    alternates=("wellness/salon|spa for beauty venues", "shop/boutique for fashion", "editorial/lifestyle + feature fallback")),
    "Spa and Wellness": _p("wellness", "spa", None, _B, ("format",), confidence="high", decisions=("D13",),
                           reasoning="Cue wellness 96%. Subtype spa dominates; retreat/yoga/salon per article (needs D13 for salon/retreat). Format per article (offer 18%, news 15%, features).",
                           alternates=("wellness/retreat for multi-day programmes", "wellness/yoga", "wellness/salon (beauty)", "format offer for spa packages")),
    "Shopping": _p("shop", "boutique", "news", _B, ("format",), confidence="medium",
                   reasoning="Mostly brand/store news and fashion features (cue shop 60%). Same prior as Jakarta Shopping.",
                   alternates=("shop/artisan for local-brand pieces", "shop/mall", "format feature/guide for style features and shopping guides")),
    "Reviews": _p("eat", "restaurant", "review", _B, (), confidence="high",
                  reasoning="Restaurant reviews; type eat 86%. Same as Jakarta Reviews.", alternates=("drink/* when the venue is a bar",)),
    "Stay Offers": _p("stay", "hotel", "offer", _B, ("subtype",), confidence="high", decisions=("D02",),
                      reasoning="Cue stay 61% / offer 88%. Subtype resort|villa per article; location is a Bali area per article.",
                      alternates=("stay/resort|villa", "wellness/retreat for spa-led packages (cue 11%)")),
    "Community": _p("editorial", "news", "feature", _B, ("format",), facets={"topic": ["community"]}, confidence="medium", decisions=("D19",), auto=False,
                    reasoning="NGO and initiative features (Solemen, Mission Paws'ible, plastic-free campaigns); evergreen features more than dated news.",
                    alternates=("event/community + event for fundraisers", "editorial/people + people for founder profiles", "format news for announcements")),
    "Opinion": _p("editorial", "opinion", "opinion", _B, (), confidence="high", decisions=("D03",),
                  reasoning="Columns (Bali's Traffic Woes, Is Bali Hindu?). Depends on approving the `opinion` format.", alternates=("topic per article",)),
    "Hotels & Resorts": _p("stay", "hotel", None, _B, ("subtype", "format"), confidence="high",
                           reasoning="Cue stay 81%. Format per article: offers (34%), news (15%), reviews/guides.",
                           alternates=("stay/resort|villa|boutique-hotel", "format offer|news|review|listing")),
    "Art In Bali": _p(None, None, None, _B, ("type", "subtype", "format"), facets={"topic": ["art"]}, confidence="medium", decisions=("D25", "D04", "D12"), auto=False,
                      reasoning="Exhibitions, artist profiles, buying guides, history of Balinese painting -- topic art is the only certain facet.",
                      alternates=("event/exhibition + event", "editorial/people + people", "editorial/culture + feature|heritage", "do/gallery + guide")),
    "Experience Offers": _p("stay", "hotel", "offer", _B, ("type", "subtype"), confidence="medium", decisions=("D17", "D02"), auto=False,
                            reasoning="Hotel experience packages: cue type splits stay 24% / eat 24% / wellness 14% / do 7%; format offer 64%.",
                            alternates=("eat/restaurant + offer (dining experiences)", "wellness/spa|retreat + offer", "event/* + event (festive programmes)")),
    "Activities": _p("do", None, "guide", _B, ("subtype", "format"), confidence="high",
                     reasoning="Things to do (cue do 66%): cooking classes, canyoning, bird walks, workshops. Subtype per article; format guide with review/offer alternates.",
                     alternates=("do/workshop|adventure|tour|watersports|attraction", "format review for first-person outings", "format offer for operator promotions (cue 21%)")),
    "Explore Bali": _p(None, None, None, _B, ("type", "subtype", "format"), confidence="low", decisions=("D18", "D10"), auto=False, container=True,
                       reasoning="Container of Activities/Cultural Sites/Destinations/Bali with Kids/Nature/Parks, plus 41 Opinion co-filings. Not a `do` category on its own.",
                       alternates=("editorial/opinion + opinion when Opinion co-occurs", "children's priors when a child co-occurs", "do/* + guide for the remainder")),
    "Culture": _p("editorial", "culture", "feature", _B, (), facets={"topic": ["culture"]}, confidence="medium", decisions=("D04",), container=True,
                  reasoning="Parent of the Culture family; the ~40 Culture-only posts are rituals, artists, gallery openings -- editorial/culture + feature is the honest fallback.",
                  alternates=("event/exhibition + event for gallery shows", "editorial/heritage + heritage for ritual explainers")),
    "Cultural Observer": _p("editorial", "culture", "feature", _B, (), facets={"topic": ["culture"]}, series_key="column:cultural-observer", confidence="high", decisions=("D04", "D24"),
                           reasoning="A long-running column on Balinese religion and society (2015-2026). Evergreen explainers.", alternates=("editorial/heritage + heritage for historical pieces",)),
    "Bar Guide": _p("drink", "bar", None, _B, ("subtype", "format"), confidence="high", decisions=("D01",),
                    reasoning="Cue drink 70%. Format per article: bar news, mixologist profiles, roundups; the guide/listing boundary (D01) decides the roundups.",
                    alternates=("drink/cocktail-bar|beach-club|rooftop-bar|pub", "format news|people|listing|review")),
    "Dance and Music": _p("editorial", "culture", "feature", _B, (), facets={"topic": ["culture", "music"]}, confidence="high", decisions=("D04", "D24"),
                         reasoning="Explainers of Balinese dance forms and gamelan (Tari Topeng, Jegog, Janger) -- not events.", alternates=("editorial/heritage + heritage",)),
    "Uncategorized": _p(None, None, None, _B, ("type", "subtype", "format"), confidence="low", decisions=("D09",), auto=False, kind="non-editorial",
                        reasoning="No prior; includes non-articles ('Purchasing NOW! Bali & TIMELESS Bali Magazines'). Review queue.", alternates=()),
    "Cultural Sites": _p("do", "attraction", "guide", _B, (), facets={"topic": ["heritage", "culture"]}, confidence="high",
                         reasoning="Temples, water palaces, sacred trees -- places to visit with a heritage angle. Prime E2.3 place-extraction input.",
                         alternates=("editorial/heritage + heritage when the piece is history-led", "format listing for roundups ('Chinese Temples in Bali')")),
    "Destinations": _p("editorial", "city-guide", "city-guide", _B, ("location",), facets={"topic": ["travel"]}, confidence="high",
                       reasoning="Area guides and itineraries (West Bali, Nusa Lembongan, East Bali road trip). Location is the Bali sub-area per article.",
                       alternates=("format listing for '3 days in X' itineraries",)),
    "Restaurant Guide": _p("eat", "restaurant", "guide", _B, ("format",), confidence="high", decisions=("D01",),
                           reasoning="Year-stamped and '[Updated]' roundups dominate since 2024 -> listing under D01; timeless area eats -> guide.",
                           alternates=("format listing + series_key for period-stamped roundups",)),
    "Bali with Kids": _p("do", None, "guide", _B, ("type", "subtype", "format"), facets={"audience": ["family"], "topic": ["family"]}, confidence="high",
                         reasoning="Audience family is the certain facet (the §4 Kids & Family example). Roundups of parks/activities -> do prior; listing when year-stamped (D01).",
                         alternates=("do/attraction|workshop + guide|listing", "stay/resort + offer for family packages")),
    "Ceremonies & Festivals": _p("editorial", "culture", "feature", _B, (), facets={"topic": ["culture"]}, confidence="high", decisions=("D04", "D24"),
                                 reasoning="Explainers of Balinese rites (Melasti, Saraswati, cremation) -- evergreen culture, not dated events.",
                                 alternates=("event/festival + event for a specific dated edition", "editorial/heritage + heritage")),
    "Travel": _p("editorial", "city-guide", "city-guide", "other", ("location", "format"), facets={"topic": ["travel"]}, confidence="medium",
                 reasoning="Archipelago Diaries: Lombok, Belitung, Sumba, Flores. Location under other/* per article; hotel promos filed here need the classifier.",
                 alternates=("stay/resort + review|offer for hotel pieces", "location international if abroad")),
    "Nature and Outdoors": _p("do", "adventure", "guide", _B, ("subtype",), confidence="high",
                              reasoning="Lakes, beaches, mangroves, hot springs -- outdoor places to go.", alternates=("do/attraction", "format listing for 'all 4 Bali lakes' roundups")),
    "People of Bali": _p("editorial", "people", "people", _B, (), confidence="high",
                         reasoning="Profiles and social portraits (farmers, priests, photographers). Evergreen per §4.", alternates=("editorial/culture + feature for group portraits",)),
    "Myths and Legends": _p("editorial", "heritage", "heritage", _B, (), facets={"topic": ["heritage", "culture"]}, confidence="high", decisions=("D24",),
                            reasoning="Folklore and origin stories -- evergreen heritage.", alternates=("editorial/culture + feature",)),
    "Everyday Bali": _p("editorial", "culture", "feature", _B, (), facets={"topic": ["culture"]}, confidence="high", decisions=("D04", "D24"),
                        reasoning="Explainers of everyday ritual objects (offerings, udeng, genta).", alternates=("editorial/heritage + heritage",)),
    "NOW! Bali Podcast": _p("editorial", "culture", "feature", _B, ("subtype",), series_key="column:podcast", kind="column", confidence="medium", decisions=("D08",), auto=False,
                            reasoning="Podcast episode pages (2020-2025). No §4 format for audio; feature + series_key keeps them browsable.", alternates=("editorial/people + people for interview episodes",)),
    "Chaine Des Rottiseurs": _p("eat", "fine-dining", "event", _B, (), series_key="column:chaine-des-rotisseurs", kind="column", confidence="medium", decisions=("D08", "D02"), auto=False,
                                reasoning="Reports on the gastronomic society's dinners (2015-2018) -- dated, expired events at fine-dining venues.", alternates=("format review", "event/community")),
    "Made in Bali": _p("shop", "artisan", "feature", _B, ("type",), facets={"topic": ["local-brands"]}, confidence="medium",
                       reasoning="Local makers: salt, arak, craft beer, seaweed farmers. Mirrors Jakarta Made In Indonesia (shop/artisan when a brand is the subject, else editorial/people).",
                       alternates=("editorial/people + people", "drink/pub|bar for brewery/distillery pieces")),
    "Bali History": _p("editorial", "heritage", "heritage", _B, (), facets={"topic": ["heritage"]}, confidence="high", decisions=("D24",),
                       reasoning="Colonial-era history, early tourism, old maps.", alternates=()),
    "Stranger In Paradise": _p("editorial", "opinion", "opinion", _B, (), series_key="column:stranger-in-paradise", kind="column", confidence="medium", decisions=("D03", "D08", "D24"),
                               reasoning="Made Wijaya's satirical society column (2015-2019): opinion with a heritage flavour.", alternates=("editorial/heritage + heritage", "editorial/culture + feature")),
    "Weddings": _p(None, None, "listing", _B, ("type", "subtype", "format"), facets={"occasion": ["celebration"]}, confidence="medium", decisions=("D22", "D01"), auto=False,
                   reasoning="Venue and service roundups for weddings/proposals; venues are villas/resorts, services are shops.", alternates=("stay/villa|resort + listing", "shop/boutique + listing", "format guide")),
    "Parks and Attractions": _p("do", "attraction", "guide", _B, ("format",), confidence="high",
                                reasoning="Zoos, waterparks, GWK, farms -- attractions.", alternates=("format review for first-person visits", "audience family")),
    "Cook and Mix": _p("editorial", "lifestyle", "feature", _B, (), series_key="column:cook-and-mix", kind="column", confidence="medium", decisions=("D08", "D05"), auto=False,
                       reasoning="Recipes and cocktail mixes (2016, 2020 lockdown). No §4 format for recipes -- E1.4 chose editorial/lifestyle + feature for Jakarta's Rice Table recipes; same here.", alternates=()),
    "Must Watch Movies": _p("editorial", "lifestyle", "feature", None, (), series_key="column:must-watch-movies", kind="column", confidence="medium", decisions=("D08", "D05"), auto=False,
                            reasoning="Lockdown movie lists with no Bali subject at all; location none. Rails should probably never surface these.", alternates=("exclude from migration",)),
    "Music to the Ears": _p("editorial", "lifestyle", "feature", None, (), series_key="column:music-to-the-ears", kind="column", confidence="medium", decisions=("D08", "D05"), auto=False,
                            reasoning="Lockdown playlists with no Bali subject; location none.", alternates=("exclude from migration",)),
    "Video": _p(None, None, None, _B, ("type", "subtype", "format"), series_key="column:video", kind="column", confidence="low", decisions=("D08",), auto=False,
                reasoning="Video posts mirroring other categories (Made in Bali, Behind the Bar, Home Workout). Classify from content.", alternates=()),
    "Winocracy": _p("editorial", "opinion", "opinion", _B, (), facets={"topic": ["food-drink"]}, series_key="column:winocracy", kind="column", confidence="high", decisions=("D03", "D08"),
                    reasoning="A wine column (2019-2020): opinion.", alternates=("drink/wine-bar when a venue is the subject",)),
    "Behind the Bar": _p("drink", "cocktail-bar", "people", _B, ("format",), series_key="column:behind-the-bar", kind="column", confidence="high", decisions=("D08",),
                         reasoning="Mixologist profiles and craft-spirit launches; child of Bar Guide.", alternates=("format news for product launches (East Indies Gin)",)),
    "Health & Wellness": _p("editorial", "lifestyle", "feature", None, (), facets={"topic": ["health"]}, series_key="column:health-wellness", kind="column", confidence="medium", decisions=("D08", "D05"), auto=False,
                            reasoning="Lockdown home-workout/yoga-at-home pieces (2020); no venue.", alternates=("wellness/yoga + guide when a studio is the subject (Yoga Barn)",)),
    "Features": _p("editorial", None, "feature", _B, ("subtype",), confidence="medium", decisions=("D27",),
                   reasoning="3 posts; long-form. Subtype per article.", alternates=()),
    "Home Life": _p("editorial", "lifestyle", "feature", None, (), series_key="column:home-life", kind="column", confidence="medium", decisions=("D08", "D27"),
                    reasoning="1 post; parent of the lockdown columns.", alternates=()),
    "Offers": _p("stay", "hotel", "offer", _B, ("subtype",), confidence="high", decisions=("D27", "D02"),
                 reasoning="1 post (a festive package). Same prior as Jakarta's Offers parent (stay/hotel + offer).", alternates=()),
    "Mapping Bali": _p(None, None, None, _B, ("type", "subtype", "format"), kind="container", confidence="low", decisions=("D27",),
                       reasoning="0 published posts (WP's count of 41 is non-post content). Nothing to map.", alternates=()),
    "Archives": _p(None, None, None, _B, ("type", "subtype", "format"), kind="container", confidence="low", decisions=("D27",),
                   reasoning="Empty parent of the column categories. Nothing to map.", alternates=()),
}

# ---------------------------------------------------------------------------
# Jakarta: amendments to E1.4. Keys are category names; values override /
# annotate the carried E1.4 prior. `decisions` links to the registry.
# ---------------------------------------------------------------------------
JAKARTA_ADJUSTMENTS: dict[str, dict] = {
    "News": {"decisions": [], "auto": True, "note": "Carried: format news, type per article. The cue instrument reads 10% event / 7% listing / 7% offer -- the classifier's override rate, not a mapping problem."},
    "Dining Offers": {"decisions": ["D02"], "auto": True, "note": "Carried. Cue offer 70% / eat 76% -- the cleanest offer category in either city. The only open point is the expiry policy (D02), which is not a mapping question."},
    "Events": {"decisions": ["D02", "D12"], "auto": True},
    "Dining News": {"decisions": [], "auto": True},
    "Stay Offers": {"decisions": ["D02"], "auto": True},
    "Art": {"decisions": ["D25", "D04", "D12"], "auto": False},
    "Reviews": {"decisions": [], "auto": True},
    "Experience Offers": {"decisions": ["D17", "D02"], "auto": False, "per_article": ["type", "subtype"],
                          "note": "Amended: E1.4 fixed type stay/hotel; the cue instrument splits stay 44% / eat 22% / wellness 12% / do 5% and the clusters agree -- type is per article with stay as the prior (D17)."},
    "Business": {"decisions": ["D26"], "auto": False, "per_article": ["format"],
                 "note": "Amended: 19% read as stay (hotel corporate news). Type prior editorial/business stays but is switchable; format per article."},
    "Education": {"decisions": [], "auto": True},
    "Explore Indonesia": {"decisions": ["D14"], "auto": True, "note": "Carried. 16% read as offers (hotel promos filed here) -- classifier override, and D14 adds the destination nodes the tree lacks."},
    "Community": {"decisions": ["D19"], "auto": False, "format": "feature", "per_article": ["format"],
                  "note": "Amended: prior format feature (D19); E1.4 had news."},
    "Opinion": {"decisions": ["D03"], "auto": True, "note": "Carried; only the vocabulary approval (D03) is open."},
    "Bali Updates": {"decisions": [], "auto": True, "note": "Carried: location bali certain, type/format per article. These 111 are the §3.5 syndication set for now_bali."},
    "Shopping": {"decisions": [], "auto": True},
    "Health": {"decisions": ["D05", "D13"], "auto": True, "note": "Carried as E1.4's recommendation (topic health always; wellness/* when a venue is the subject, else editorial/lifestyle) -- only the vocabulary approvals are open."},
    "NOW! People": {"decisions": [], "auto": True},
    "World Traveller": {"decisions": ["D06"], "auto": True, "note": "Carried; only the `international` root approval (D06) is open."},
    "Uncategorized": {"decisions": ["D09"], "auto": False},
    "History & Heritage": {"decisions": ["D14"], "auto": True},
    "Culture": {"decisions": ["D04"], "auto": True, "note": "Carried; depends on D04 only."},
    "Sports & Activities": {"decisions": ["D11"], "auto": True, "note": "Carried as E1.4's recommendation; only the subtype approval (D11) is open."},
    "Offers": {"decisions": ["D02"], "auto": True},
    "Music": {"decisions": ["D02"], "auto": True},
    "Green Living": {"decisions": ["D05"], "auto": True},
    "Kids & Family": {"decisions": [], "auto": True},
    "Made In Indonesia": {"decisions": [], "auto": True},
    "Film": {"decisions": ["D12"], "auto": True, "note": "Carried as E1.4's recommendation (event/screening); only D12 is open."},
    "Art & Culture": {"decisions": ["D04", "D10"], "auto": True, "note": "Parent container used directly since 2023; topic art/culture only, everything else per article. D10 makes it moot when a child is present."},
    "Bar Guide": {"decisions": ["D01"], "auto": True, "format": None, "per_article": ["format", "subtype"],
                  "note": "Amended: E1.4 fixed format guide; the cue instrument reads 53% of the signal-bearing pieces as news (openings, product launches) and the titles agree -- type drink stays, format is per article with the roundups decided by D01."},
    "Design": {"decisions": ["D04"], "auto": True},
    "Dining": {"decisions": ["D01", "D10"], "auto": True},
    "Discover Jakarta": {"decisions": ["D10", "D14"], "auto": True},
    "Travel": {"decisions": ["D06", "D14"], "auto": True},
    "Features": {"decisions": ["D10"], "auto": True},
    "City Guides": {"decisions": ["D01"], "auto": True, "note": "Carried as E1.4's recommendation: NOT format city-guide -- venue roundups typed per article; guide or listing under D01."},
    "Restaurant Guides": {"decisions": ["D01"], "auto": True, "format": None, "per_article": ["format"],
                          "note": "Amended: E1.4 fixed format guide; 13 of 17 are 2024+ period-stamped roundups ('[Updated]', year in title) plus two news items -- type eat stays, format is per article with D01 deciding the roundups. Mirrors Bali Restaurant Guide."},
    "Hidden Heritage": {"decisions": ["D14"], "auto": True},
    "Lifestyle": {"decisions": ["D05"], "auto": True, "format": None, "per_article": ["type", "subtype", "format"],
                  "note": "Amended: 13 posts since 2023, a grab-bag (duty-free shop, pottery workshop, serviced residences, mahjong); no honest type or format prior -- editorial/lifestyle is only the fallback (D05)."},
    "Sites & Destinations": {"decisions": [], "auto": True},
    "Diplomatic Relations": {"decisions": [], "auto": True},
}

# Bali parent containers (from the REST harvest hierarchy) -- used for D10 evidence.
CONTAINERS = {
    "bali": ["Lifestyle", "Restaurants and Bars", "Culture", "Explore Bali", "Offers", "Features", "Archives", "Home Life", "Bar Guide"],
    "jakarta": ["Offers", "Dining", "Art & Culture", "Features", "Lifestyle", "Travel", "Discover Jakarta", "Explore Indonesia", "Magazine Issue"],
}
